### ISSUE TITLE
parallelStream于EL表达式解析不兼容

### ISSUE THREAD

**Issue by ApostleTubriss** [PowerJob/PowerJob#1002]
**Describe the bug**
当状态检查任务并行运行时，异步任务会报错类未定义
Type cannot be found 'tech.powerjob.common.enums.TimeExpressionType'

目前定位原因是因为parallelStream使用了ForkJoinPool线程池，其默认的类加载器为
ClassLoader#getSystemClassLoader()
这里获取到的是AppClassLoader

AOPUtil中的EL表达式解析使用了默认构造上下文StandardEvaluationContext，其typeLocator为StandardTypeLocator
默认情况其使用的cl为线程上下文中的cl
cl = Thread.currentThread().getContextClassLoader();

当parallelStream并行运行时，异步线程的上下文cl为AppClassLoader

而TimeExpressionType类所使用的类加载器为LaunchedClassLoader，EL解析类找不到

参考
https://github.com/spring-projects/spring-framework/issues/26253

应该是并行流+EL表达式解析+自定义类 的兼容问题
目前我们的解决方案是强制FJP串行运行
-Djava.util.concurrent.ForkJoinPool.common.parallelism=0

可能的修改方案为
手动指定TypeLocator
or
将并行流改为Executor线程池运行？

**To Reproduce**
1、线上环境运行
2、同时存在多个检查任务

**Expected behavior**
多个检查任务都能成功执行

**Environment**
 - PowerJob Version: 4.3.6
 - Java Version: OpenJDK 17
 - OS: Ubuntu 20.04

**Screenshots**
![image](https://github.com/user-attachments/assets/84c0e85a-774d-4c20-9a90-52a1361245d5)

**Additional context**
message:[AOPUtils] parse SpEL failed for method[dispatch], please concat @tjq to fix the bug!
org.springframework.expression.spel.SpelEvaluationException: EL1005E: Type cannot be found 'tech.powerjob.common.enums.TimeExpressionType'
at org.springframework.expression.spel.support.StandardTypeLocator.findType(StandardTypeLocator.java:117)
at org.springframework.expression.spel.ExpressionState.findType(ExpressionState.java:180)
at org.springframework.expression.spel.ast.TypeReference.getValueInternal(TypeReference.java:69)
at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:56)
at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:92)
at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:212)
at org.springframework.expression.spel.ast.OpOr.getBooleanValue(OpOr.java:56)
at org.springframework.expression.spel.ast.OpOr.getValueInternal(OpOr.java:51)
at org.springframework.expression.spel.ast.OpOr.getValueInternal(OpOr.java:37)
at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:212)
at org.springframework.expression.spel.ast.Ternary.getValueInternal(Ternary.java:54)
at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:119)
at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:309)
at tech.powerjob.server.common.utils.AOPUtils.parseSpEl(AOPUtils.java:62)
at tech.powerjob.server.core.lock.UseCacheLockAspect.execute(UseCacheLockAspect.java:56)
at jdk.internal.reflect.GeneratedMethodAccessor197.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
at tech.powerjob.server.core.DispatchService$$EnhancerBySpringCGLIB$$c921ad7a.dispatch(<generated>)
at tech.powerjob.server.core.scheduler.InstanceStatusCheckService.lambda$handleWaitingDispatchInstance$2(InstanceStatusCheckService.java:175)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165),

**Comment by KFCFans** [comment]
感谢反馈，确实是明确的问题，会尽快修复。

**Comment by hanisem151** [comment]
这个bug现在解决了吗？
