### ISSUE TITLE
调度任务参数中【运行时间限制】的配置不生效，超过限制时间仍然还在执行

### ISSUE THREAD

**Issue by linwei-scholar** [PowerJob/PowerJob#1053]
**Describe the bug**
调度任务参数中【运行时间限制】的配置不生效

**To Reproduce**
新建调度任务，填写【运行时间限制（毫秒）】为10000即10秒，但是任务实际执行超过10秒后仍然不会以失败结束，配置无法生效。

**Environment**
 - PowerJob Version: [4.3.5]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**
任务配置：
```JSON
{"id":null,"jobName":"测试-02-RestAPI-官方处理器","jobDescription":"01-测试RestAPI","appId":null,"jobParams":"{\"method\":\"GET\",\"url\":\"http://10.xxx.xxx.00\"}","timeExpressionType":"CRON","timeExpression":"0/30 * * * * ?","executeType":"STANDALONE","processorType":"BUILT_IN","processorInfo":"tech.powerjob.official.processors.impl.HttpProcessor","maxInstanceNum":0,"concurrency":5,"instanceTimeLimit":10000,"instanceRetryNum":0,"taskRetryNum":0,"minCpuCores":0,"minMemorySpace":0,"minDiskSpace":0,"enable":true,"designatedWorkers":"","maxWorkerCount":0,"notifyUserIds":null,"extra":null,"dispatchStrategy":"HEALTH_FIRST","lifeCycle":{"start":null,"end":null},"alarmConfig":{"alertThreshold":0,"statisticWindowLen":0,"silenceWindowLen":0},"tag":null,"logConfig":{"type":null,"level":null,"loggerName":null}}
```
执行记录：
```bash
2024-12-24 14:28:42.468 [10.xxxx:xx] INFO using params: {"method":"GET","url":"http://10.xxx.xxx.00"}
2024-12-24 14:28:42.468 [10.xxxx:xx] INFO request url: http://10.xxx.xxx.00
2024-12-24 14:28:42.468 [10.xxxx:xx] INFO request method: GET
2024-12-24 14:28:42.468 [10.xxxx:xx] INFO request timeout: 60 seconds
2024-12-24 14:29:42.469 [10.xxxx:xx] ERROR execute failed!
java.io.InterruptedIOException: timeout
at shade.powerjob.okhttp3.internal.connection.Transmitter.timeoutExit(Transmitter.java:109)
at shade.powerjob.okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:302)
```

**Comment by linwei-scholar** [comment]
跟了一下源码，发现任务的超时结束收到一个环境变量值的影响，`tech.powerjob.worker.core.tracker.task.light.LightTaskTracker#tryForceStopThread` : `powerjob.worker.allowed-force-stop-thread` ; 配置了环境变量为 `true` 后，超时限制才生效。
**解决办法**：启动worker时指定环境变量：`-Dpowerjob.worker.allowed-force-stop-thread=true`
