### ISSUE TITLE
Caused by: java.lang.InterruptedException: null

### ISSUE THREAD

**Issue by andychyiyi** [PowerJob/PowerJob#1054]
- 4.0.1
- 容器化环境
- http处理器的任务

1. 流畅运行很久后出现的这个问题。
2. 2024.12.20之前一直正常，没有任何错误。2024.12.20之后轻量级的任务偶尔出现这个问题，重一点点的ftp任务就会出现这个超时的问题。
3. 任务下发正常，任务执行完成之后汇报状态失败。
4. 心跳偶尔也会出现失败的现象导致不能无可用worker。

请问是什么问题。

log-----

2024-12-23 09:47:04 [ctttp-751377141718844096-0] WARN  tech.powerjob.worker.core.tracker.task.CommonTaskTracker.312 - [TaskTracker-751377141718844096] some ProcessorTracker disconnected from TaskTracker,their address is [xxx-datatransfer.xxx.svc:30069].
2024-12-23 09:47:04 [ctttp-751377141718844096-0] WARN  tech.powerjob.worker.core.tracker.task.CommonTaskTracker.315 - [TaskTracker-751377141718844096] removed these ProcessorTracker from StatusHolder: [xxx-datatransfer.xxx.svc:30069]
2024-12-23 09:47:04 [ctttp-751377141706261185-0] WARN  tech.powerjob.worker.core.tracker.task.CommonTaskTracker.302 - [TaskTracker-751377141706261185] task(id=0,name=OMS_ROOT_TASK) try to dispatch again due to unreceived the response from ProcessorTracker.
2024-12-23 09:47:04 [ctttp-751377141706261185-0] WARN  tech.powerjob.worker.core.tracker.task.CommonTaskTracker.312 - [TaskTracker-751377141706261185] some ProcessorTracker disconnected from TaskTracker,their address is [xxx-datatransfer.xxx.svc:30069].
2024-12-23 09:47:04 [com.alibaba.nacos.naming.push.receiver] INFO  com.alibaba.nacos.client.naming.86 - received push data: {"type":"dom","data":"{\"name\":\"wireless-workbench-base@@xxx4xxxDatatransfer\",\"clusters\":\"DEFAULT\",\"cacheMillis\":10000,\"hosts\":[],\"lastRefTime\":1734918375046,\"checksum\":\"\",\"allIPs\":false,\"reachProtectionThreshold\":false,\"valid\":true}","lastRefTime":4744848000468533} from /172.16.115.96
2024-12-23 09:47:04 [ctttp-751377141706261185-0] WARN  tech.powerjob.worker.core.tracker.task.CommonTaskTracker.315 - [TaskTracker-751377141706261185] removed these ProcessorTracker from StatusHolder: [xxx-datatransfer.xxx.svc:30069]
2024-12-23 09:47:04 [com.alibaba.nacos.naming.push.receiver] INFO  com.alibaba.nacos.client.naming.86 - received push data: {"type":"dom","data":"{\"name\":\"wireless-workbench-base@@xxx4xxxDatatransfer\",\"clusters\":\"DEFAULT\",\"cacheMillis\":10000,\"hosts\":[],\"lastRefTime\":1734918375046,\"checksum\":\"\",\"allIPs\":false,\"reachProtectionThreshold\":false,\"valid\":true}","lastRefTime":4744848000468533} from /172.16.115.96
2024-12-23 09:47:04 [oms-akka.processor-tracker-dispatcher-942] WARN  tech.powerjob.worker.core.tracker.processor.ProcessorTracker.341 - [ProcessorTracker-751377141706261185] no spring bean of processor(className=tech.powerjob.official.processors.impl.HttpProcessor), reason is NoSuchBeanDefinitionException: No qualifying bean of type 'tech.powerjob.official.processors.impl.HttpProcessor' available.
2024-12-23 09:47:04 [oms-akka.processor-tracker-dispatcher-942] INFO  tech.powerjob.worker.core.tracker.processor.ProcessorTracker.131 - [ProcessorTracker-751377141706261185] ProcessorTracker was successfully created!
2024-12-23 09:47:04 [oms-akka.task-tracker-dispatcher-1606] WARN  tech.powerjob.worker.actors.TaskTrackerActor.146 - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918424164, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:47:04 [oms-akka.task-tracker-dispatcher-1606] WARN  tech.powerjob.worker.actors.TaskTrackerActor.146 - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918424164, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:47:04 [oms-akka.task-tracker-dispatcher-1606] WARN  tech.powerjob.worker.actors.TaskTrackerActor.146 - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918424164, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:47:04 [oms-akka.task-tracker-dispatcher-1606] WARN  tech.powerjob.worker.actors.TaskTrackerActor.146 - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918424164, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:47:04 [oms-akka.task-tracker-dispatcher-1606] WARN  tech.powerjob.worker.actors.TaskTrackerActor.146 - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918424164, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:47:04 [oms-akka.task-tracker-dispatcher-1606] WARN  tech.powerjob.worker.actors.TaskTrackerActor.70 - [TaskTrackerActor] receive ProcessorReportTaskStatusReq(ProcessorReportTaskStatusReq(instanceId=751377141706261185, subInstanceId=751377141706261185, taskId=0, status=3, result=null, reportTime=1734918424165, cmd=null, appendedWfContext=null)) but system can't find TaskTracker.
2024-12-23 09:47:04 [oms-akka.task-tracker-dispatcher-1719] WARN  tech.powerjob.worker.actors.TaskTrackerActor.70 - [TaskTrackerActor] receive ProcessorReportTaskStatusReq(ProcessorReportTaskStatusReq(instanceId=751377141706261185, subInstanceId=751377141706261185, taskId=0, status=4, result=null, reportTime=1734918424166, cmd=null, appendedWfContext=null)) but system can't find TaskTracker.
2024-12-23 09:47:04 [oms-akka.task-tracker-dispatcher-1605] INFO  tech.powerjob.worker.core.tracker.task.TaskTracker.139 - [TaskTracker-751377393364501184] create TaskTracker successfully.
2024-12-23 09:47:04 [oms-akka.processor-tracker-dispatcher-1407] WARN  tech.powerjob.worker.core.tracker.processor.ProcessorTracker.341 - [ProcessorTracker-751377141718844096] no spring bean of processor(className=tech.powerjob.official.processors.impl.HttpProcessor), reason is NoSuchBeanDefinitionException: No qualifying bean of type 'tech.powerjob.official.processors.impl.HttpProcessor' available.
2024-12-23 09:47:04 [oms-akka.processor-tracker-dispatcher-1407] INFO  tech.powerjob.worker.core.tracker.processor.ProcessorTracker.131 - [ProcessorTracker-751377141718844096] ProcessorTracker was successfully created!
2024-12-23 09:47:04 [oms-akka.task-tracker-dispatcher-23] WARN  tech.powerjob.worker.core.ha.ProcessorTrackerStatusHolder.41 - [ProcessorTrackerStatusHolder] unregistered worker: xxx-datatransfer.xxx.svc:30069
2024-12-23 09:47:04 [PPP-2] INFO  tech.powerjob.official.processors.CommonBasicProcessor.48 - HttpProcessor|2000093|751365818972897985|exception|20.35 min
2024-12-23 09:47:04 [PPP-2] WARN  tech.powerjob.worker.common.utils.AkkaUtils.50 - [PowerTransmitter] transmit ProcessorReportTaskStatusReq(instanceId=751365818972897985, subInstanceId=751365818972897985, taskId=0, status=5, result=InterruptedIOException: timeout, reportTime=1734918424444, cmd=null, appendedWfContext={}) failed
tech.powerjob.common.exception.PowerJobException: java.lang.InterruptedException
	at tech.powerjob.worker.common.utils.AkkaUtils.easyAsk(AkkaUtils.java:60)
	at tech.powerjob.worker.common.utils.AkkaUtils.reliableTransmit(AkkaUtils.java:48)
	at tech.powerjob.worker.core.executor.ProcessorRunnable.reportStatus(ProcessorRunnable.java:225)
	at tech.powerjob.worker.core.executor.ProcessorRunnable.innerRun(ProcessorRunnable.java:104)
	at tech.powerjob.worker.core.executor.ProcessorRunnable.run(ProcessorRunnable.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:91)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:91)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.package$.blocking(package.scala:124)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:91)
	at tech.powerjob.worker.common.utils.AkkaUtils.easyAsk(AkkaUtils.java:58)
	... 9 common frames omitted
2024-12-23 09:47:04 [PPP-2] WARN  tech.powerjob.worker.core.executor.ProcessorRunnable.229 - [ProcessorRunnable-751365818972897985] report task(id=0,status=WORKER_PROCESS_FAILED,result=InterruptedIOException: timeout) failed, will retry later
2024-12-23 09:48:01 [HikariPool-1 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool.? - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m47s541ms346µs480ns).
2024-12-23 09:48:01 [Server-Hikari housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool.? - Server-Hikari - Thread starvation or clock leap detected (housekeeper delta=57s393ms965µs164ns).
2024-12-23 09:48:01 [http-nio-6025-exec-286] INFO  com.xxx.datatransfer.common.util.FtpUtil.? - FTP连接成功
2024-12-23 09:48:01 [com.alibaba.nacos.client.naming.updater] WARN  com.alibaba.nacos.client.naming.? - out of date data received, old-t: 1734918375046, new-t: 1734918374447
2024-12-23 09:48:01 [http-nio-6025-exec-278] INFO  com.xxx.datatransfer.common.util.FtpUtil.128 - FTP连接成功
2024-12-23 09:48:01 [http-nio-6025-exec-291] INFO  com.xxx.datatransfer.common.util.FtpUtil.? - FTP连接成功
2024-12-23 09:48:01 [http-nio-6025-exec-293] INFO  com.xxx.datatransfer.common.util.FtpUtil.128 - FTP连接成功
2024-12-23 09:48:01 [oms-akka.task-tracker-dispatcher-606] WARN  tech.powerjob.worker.actors.TaskTrackerActor.? - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918481436, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:48:01 [http-nio-6025-exec-20] INFO  com.xxx.datatransfer.common.util.FtpUtil.128 - FTP连接成功
2024-12-23 09:48:01 [oms-akka.task-tracker-dispatcher-1298] WARN  tech.powerjob.worker.actors.TaskTrackerActor.? - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918481436, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:48:01 [oms-akka.task-tracker-dispatcher-482] WARN  tech.powerjob.worker.actors.TaskTrackerActor.? - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918481436, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:48:01 [oms-akka.task-tracker-dispatcher-349] WARN  tech.powerjob.worker.actors.TaskTrackerActor.? - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918481436, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:48:01 [oms-akka.task-tracker-dispatcher-1294] INFO  tech.powerjob.worker.core.tracker.task.CommonTaskTracker.135 - [TaskTracker-751377896689369793] create root task successfully.
2024-12-23 09:48:01 [oms-akka.task-tracker-dispatcher-1379] WARN  tech.powerjob.worker.actors.TaskTrackerActor.? - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918481436, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:48:01 [oms-akka.task-tracker-dispatcher-1379] WARN  tech.powerjob.worker.actors.TaskTrackerActor.130 - [TaskTrackerActor] TaskTracker(CommonTaskTracker(reportFailedCnt=0)) for instance(id=751377645031129792) already exists.
2024-12-23 09:48:01 [oms-akka.task-tracker-dispatcher-341] WARN  tech.powerjob.worker.actors.TaskTrackerActor.? - [TaskTrackerActor] receive ProcessorTrackerStatusReportReq(ProcessorTrackerStatusReportReq(type=2, instanceId=751377141706261185, time=1734918481436, remainTaskNum=0, address=xxx-datatransfer.xxx.svc:30069)) but system can't find TaskTracker.
2024-12-23 09:48:01 [http-nio-6025-exec-544] INFO  com.xxx.datatransfer.common.util.FtpUtil.? - FTP连接成功
2024-12-23 09:48:01 [http-nio-6025-exec-456] INFO  com.xxx.datatransfer.common.util.FtpUtil.? - FTP连接成功
2024-12-23 09:48:01 [ctttp-751377393364501184-1] WARN  tech.powerjob.worker.core.tracker.task.CommonTaskTracker.? - [TaskTracker-751377393364501184] task(id=0,name=OMS_ROOT_TASK) try to dispatch again due to unreceived the response from ProcessorTracker.
2024-12-23 09:48:01 [ctttp-751377645031129792-0] WARN  tech.powerjob.worker.core.tracker.task.CommonTaskTracker.? - [TaskTracker-751377645031129792] task(id=0,name=OMS_ROOT_TASK) try to dispatch again due to unreceived the response from ProcessorTracker.
2024-12-23 09:48:01 [PPP-2] INFO  tech.powerjob.official.processors.CommonBasicProcessor.? - HttpProcessor|2000050|751365818901594817|exception|20.42 min
2024-12-23 09:48:01 [PPP-2] WARN  tech.powerjob.worker.common.utils.AkkaUtils.50 - [PowerTransmitter] transmit ProcessorReportTaskStatusReq(instanceId=751365818901594817, subInstanceId=751365818901594817, taskId=0, status=5, result=InterruptedIOException: timeout, reportTime=1734918481513, cmd=null, appendedWfContext={}) failed
tech.powerjob.common.exception.PowerJobException: java.lang.InterruptedException
	at tech.powerjob.worker.common.utils.AkkaUtils.easyAsk(AkkaUtils.java:60)
	at tech.powerjob.worker.common.utils.AkkaUtils.reliableTransmit(AkkaUtils.java:48)
	at tech.powerjob.worker.core.executor.ProcessorRunnable.reportStatus(ProcessorRunnable.java:225)
	at tech.powerjob.worker.core.executor.ProcessorRunnable.innerRun(ProcessorRunnable.java:104)
	at tech.powerjob.worker.core.executor.ProcessorRunnable.run(ProcessorRunnable.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:91)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:91)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.package$.blocking(package.scala:124)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:91)
	at tech.powerjob.worker.common.utils.AkkaUtils.easyAsk(AkkaUtils.java:58)
	... 9 common frames omitted

**Comment by KFCFans** [comment]
akka 的问题一般多是网络问题，如果网络问题不好排查，可以考虑切换到通用的 http 协议，辅以一些网络监控。

**Comment by andychyiyi** [comment]
[ WARN] tech.powerjob.worker.core.tracker.task.CommonTaskTracker    :  312 - [TaskTracker-813345407831639616] some ProcessorTracker disconnected from TaskTracker,their address is  xxxx

 [ WARN] tech.powerjob.worker.core.tracker.task.CommonTaskTracker    :  315 - [TaskTracker-813345407831639616] removed these ProcessorTracker from StatusHolder:xxxxx


版本 4.0.1
记录一下这个日志导致的可能的原因
任务（如ftp任务）执行过程中，网络负载过载且时间过长（超 3-5 分钟），导致worker 给到 server 的通信受阻，
建议加大 jvm的初始内存和最大内存“-Xms4g -Xmx16g”用来缓解负载问题。
核心思想就是，别让 worker 的 CPU、内存占用拉满、严重会导致worker卡死，轻微会导致通信受阻，需要资源分配
