### ISSUE TITLE
TaskTracker 82行属性copy不匹配

### ISSUE THREAD

**Issue by f123ma** [PowerJob/PowerJob#177]
BeanUtils.copyProperties(ServerScheduleJobReq,InstanceInfo)
timeExpressionType一个为String一个为Int
具体异常信息如下：
`org.springframework.beans.FatalBeanException: Could not copy properties from source to target; nested exception is java.lang.IllegalArgumentException: argument type mismatch
	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:621)
	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:531)
	at com.github.kfcfans.powerjob.worker.core.tracker.task.TaskTracker.<init>(TaskTracker.java:82)
	at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker.<init>(CommonTaskTracker.java:45)
	at com.github.kfcfans.powerjob.worker.core.tracker.task.TaskTracker.create(TaskTracker.java:120)
	at com.github.kfcfans.powerjob.worker.actors.TaskTrackerActor.lambda$8(TaskTrackerActor.java:123)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at com.github.kfcfans.powerjob.worker.core.tracker.task.TaskTrackerPool.atomicCreateTaskTracker(TaskTrackerPool.java:32)
	at com.github.kfcfans.powerjob.worker.actors.TaskTrackerActor.onReceiveServerScheduleJobReq(TaskTrackerActor.java:123)`

**Comment by KFCFans** [comment]
提供下server和worker的版本

**Comment by KFCFans** [comment]
我查了一些资料都表示 Spring 的 BeanUtils 在类型不一致的情况下会直接忽略该字段，而不是抛出异常。
这些代码基本也是从 1.0 版本到现在从来没变过。

目前为止只出现了你这一个 case，辛苦看下你本地 BeanUtils 实际依赖的库版本，估计是类冲突导致的。

**Comment by f123ma** [comment]
确实是这个问题，老版本3.2.4的spring beans没有匹配类型，框架所用版本的5.2.4做了类型校验，老版本依赖删除解决这个问题
