### ISSUE TITLE
关于server线程相关的问题

### ISSUE THREAD

**Issue by wangzgBoom** [PowerJob/PowerJob#213]
因为节前测试环境关闭，在本地搭了个demo进行小规模测试，创建了40个任务，跑了大概3个小时，出现了oom
贴出相关jvm监控数据：

![image](https://user-images.githubusercontent.com/26318180/107303092-61f6f280-6ab9-11eb-819f-d6f74b80756d.png)
![image](https://user-images.githubusercontent.com/26318180/107303232-a3879d80-6ab9-11eb-9323-670ded88a765.png)
![image](https://user-images.githubusercontent.com/26318180/107303273-bac68b00-6ab9-11eb-8185-81c7b043c513.png)

1. 为什么server在运行后线程数一直飙升，而不是运行一段时间后进入稳定期
2. HashedWheelTimer-Executor-xxx 线程应该是时间轮调度相关，为什么创建了这么多，一共40个Cron单机任务，每15s执行一次
感觉不太合理
3. Thread-xxx   看不出这个线程具体是干什么的，数量最多的就是这个，很多都是创建时running状态一小段时间后就进入park，一直到jvm崩溃，如果线程不活动是否应该时关闭

另外一个原因可能是我本地环境性能不行，但是出现这情况感觉还是需要分析一下

**Comment by KFCFans** [comment]
非常感谢提供那么详细的数据，我仔细分析下。

**Comment by KFCFans** [comment]
顺便问一句，日志还在吗？如果有日志的话，可以搜索下关键字 `overload` ，顺便看看有没有奇怪的 warn 告警

**Comment by KFCFans** [comment]
还有要是有直接的内存和线程 dump 文件就更好了。

**Comment by wangzgBoom** [comment]
找了一下线程开始飙升的时候的日志,
server端:
2021-02-09 14:48:53.893  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-15] schedule delay, expect: 1612853025000, current: 1612853333893
2021-02-09 14:48:53.893  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-16] schedule delay, expect: 1612853025000, current: 1612853333893
2021-02-09 14:48:53.894  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-17] schedule delay, expect: 1612853040000, current: 1612853333894
2021-02-09 14:48:53.894  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-18] schedule delay, expect: 1612853025000, current: 1612853333894
2021-02-09 14:48:53.894  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-21] schedule delay, expect: 1612852920000, current: 1612853333894
2021-02-09 14:48:53.894  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-22] schedule delay, expect: 1612852935000, current: 1612853333894
2021-02-09 14:48:53.894  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-23] schedule delay, expect: 1612852650000, current: 1612853333894
2021-02-09 14:48:53.894  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-24] schedule delay, expect: 1612852965000, current: 1612853333894
2021-02-09 14:48:53.894  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-25] schedule delay, expect: 1612852965000, current: 1612853333894
2021-02-09 14:48:53.894  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-26] schedule delay, expect: 1612852980000, current: 1612853333894
2021-02-09 14:48:53.894  WARN 20612 --- [     Thread-157] c.g.k.p.s.s.t.s.OmsScheduleService       : [Job-27] schedule delay, expect: 1612852980000, current: 1612853333894
2021-02-09 14:48:53.894  WARN 20612 --- [     Thread-157] .k.p.s.c.RejectedExecutionHandlerFactory : [PowerJobTimeWheelPool] ThreadPool[java.util.concurrent.ThreadPoolExecutor@6abb16ed[Running, pool size = 64, active threads = 64, queued tasks = 16, completed tasks = 8491]] overload, the task[java.util.concurrent.FutureTask@42ed495e] will run by caller thread!
2021-02-09 14:48:53.895  WARN 20612 --- [     Thread-157] .k.p.s.c.RejectedExecutionHandlerFactory : [PowerJobTimeWheelPool] Maybe you need to adjust the ThreadPool config!
2021-02-09 14:48:54.213  WARN 20612 --- [      Thread-41] c.g.k.p.server.service.DispatchService   : [Dispatcher-10|239394634038509632] cancel dispatch job due to no worker available, clusterStatus is appName:wang,clusterStatus:{192.168.64.1:27777=SystemMetrics(cpuProcessors=4, cpuLoad=-1.0, jvmUsedMemory=0.1712, jvmMaxMemory=1.7554, jvmMemoryUsage=0.0975, diskUsed=132.4215, diskTotal=465.7607, diskUsage=0.2843, score=4)}.
2021-02-09 14:48:54.925  WARN 20612 --- [-dispatcher-285] c.g.k.p.s.s.instance.InstanceManager     : [InstanceManager-239394235642544192] receive the other TaskTracker's report: TaskTrackerReportInstanceStatusReq(jobId=28, instanceId=239394235642544192, wfInstanceId=null, instanceStatus=5, result=job success, totalTaskNum=1, succeedTaskNum=1, failedTaskNum=0, startTime=1612852445161, reportTime=1612852538190, sourceAddress=192.168.64.1:27777), but current TaskTracker is N/A, this report will br dropped.
2021-02-09 14:48:55.674  WARN 20612 --- [mer-Executor-53] c.g.k.p.server.service.DispatchService   : [Dispatcher-20|239398952451964992] cancel dispatch job due to no worker available, clusterStatus is appName:wang,clusterStatus:{192.168.64.1:27777=SystemMetrics(cpuProcessors=4, cpuLoad=-1.0, jvmUsedMemory=0.1712, jvmMaxMemory=1.7554, jvmMemoryUsage=0.0975, diskUsed=132.4215, diskTotal=465.7607, diskUsage=0.2843, score=4)}.
2021-02-09 14:48:56.752  WARN 20612 --- [imer-Executor-8] c.g.k.p.server.service.DispatchService   : [Dispatcher-25|239399359488196673] cancel dispatch job due to no worker available, clusterStatus is appName:wang,clusterStatus:{192.168.64.1:27777=SystemMetrics(cpuProcessors=4, cpuLoad=-1.0, jvmUsedMemory=0.1712, jvmMaxMemory=1.7554, jvmMemoryUsage=0.0975, diskUsed=132.4215, diskTotal=465.7607, diskUsage=0.2843, score=4)}.
2021-02-09 14:48:57.322  WARN 20612 --- [mer-Executor-22] c.g.k.p.server.service.DispatchService   : [Dispatcher-18|239398940313649216] cancel dispatch job due to no worker available, clusterStatus is appName:wang,clusterStatus:{192.168.64.1:27777=SystemMetrics(cpuProcessors=4, cpuLoad=-1.0, jvmUsedMemory=0.1712, jvmMaxMemory=1.7554, jvmMemoryUsage=0.0975, diskUsed=132.4215, diskTotal=465.7607, diskUsage=0.2843, score=4)}.
2021-02-09 14:48:57.325  WARN 20612 --- [-dispatcher-273] c.g.k.p.s.s.instance.InstanceManager     : [InstanceManager-239398718212669505] receive the expired status report request: TaskTrackerReportInstanceStatusReq(jobId=7, instanceId=239398718212669505, wfInstanceId=null, instanceStatus=5, result=job success, totalTaskNum=1, succeedTaskNum=1, failedTaskNum=0, startTime=1612853213883, reportTime=1612853216885, sourceAddress=192.168.64.1:27777), this report will be dropped.
2021-02-09 14:48:57.503  WARN 20612 --- [imer-Executor-5] c.g.k.p.server.service.DispatchService   : [Dispatcher-19|239398948047945792] cancel dispatch job due to no worker available, clusterStatus is appName:wang,clusterStatus:{192.168.64.1:27777=SystemMetrics(cpuProcessors=4, cpuLoad=-1.0, jvmUsedMemory=0.1712, jvmMaxMemory=1.7554, jvmMemoryUsage=0.0975, diskUsed=132.4215, diskTotal=465.7607, diskUsage=0.2843, score=4)}.
2021-02-09 14:48:57.813  WARN 20612 --- [-dispatcher-282] c.g.k.p.s.s.instance.InstanceManager     : [InstanceManager-239394242953216064] receive the other TaskTracker's report: TaskTrackerReportInstanceStatusReq(jobId=30, instanceId=239394242953216064, wfInstanceId=null, instanceStatus=5, result=job success, totalTaskNum=1, succeedTaskNum=1, failedTaskNum=0, startTime=1612852456390, reportTime=1612852549416, sourceAddress=192.168.64.1:27777), but current TaskTracker is N/A, this report will br dropped.
2021-02-09 14:48:57.893  WARN 20612 --- [SchedulerPool-1] .k.p.s.c.RejectedExecutionHandlerFactory : [PowerJobTimingPool] ThreadPool[java.util.concurrent.ThreadPoolExecutor@4a79cd7c[Running, pool size = 16, active threads = 16, queued tasks = 0, completed tasks = 434]] overload, the task[java.util.concurrent.FutureTask@61855389] will run by a new thread!
2021-02-09 14:48:57.893  WARN 20612 --- [SchedulerPool-1] .k.p.s.c.RejectedExecutionHandlerFactory : [PowerJobTimingPool] Maybe you need to adjust the ThreadPool config!

worker端：
2021-02-09 14:48:59.983 ERROR 6684 --- [8554026639424-1] c.g.k.p.w.c.t.task.CommonTaskTracker     : [TaskTracker-239398554026639424] try to report finished status(success=true, result=job success) lots of times but all failed, it's time to give up, so the process result will be dropped
2021-02-09 14:48:59.983 ERROR 6684 --- [8769701945408-1] c.g.k.p.w.c.t.task.CommonTaskTracker     : [TaskTracker-239398769701945408] try to report finished status(success=true, result=job success) lots of times but all failed, it's time to give up, so the process result will be dropped
2021-02-09 14:48:59.983  INFO 6684 --- [r-dispatcher-62] c.g.k.p.w.c.t.p.ProcessorTracker         : [ProcessorTracker-239398554026639424] ProcessorTracker destroyed successfully!
2021-02-09 14:48:59.989  INFO 6684 --- [r-dispatcher-62] c.g.k.p.w.c.t.p.ProcessorTracker         : [ProcessorTracker-239398769701945408] ProcessorTracker destroyed successfully!
2021-02-09 14:48:59.989  INFO 6684 --- [8769701945408-1] c.g.k.p.w.core.tracker.task.TaskTracker  : [TaskTracker-239398769701945408] TaskTracker has left the world(using 414.2 μs), bye~
2021-02-09 14:48:59.983  INFO 6684 --- [8554026639424-1] c.g.k.p.w.core.tracker.task.TaskTracker  : [TaskTracker-239398554026639424] TaskTracker has left the world(using 360.3 μs), bye~
2021-02-09 14:49:00.019  WARN 6684 --- [t-dispatcher-85] c.g.k.p.w.actors.TroubleshootingActor    : [TroubleshootingActor] receive DeadLetter: DeadLetter(AskResponse(success=true, data=null, message=null),Actor[akka://oms-server@192.168.64.1:10086/user/server_actor/$c#1054657948],Actor[akka://oms/temp/$oyc])
2021-02-09 14:49:00.020  WARN 6684 --- [t-dispatcher-86] c.g.k.p.w.actors.TroubleshootingActor    : [TroubleshootingActor] receive DeadLetter: DeadLetter(AskResponse(success=true, data=null, message=null),Actor[akka://oms-server@192.168.64.1:10086/user/server_actor/$f#-836274775],Actor[akka://oms/temp/$yBc])
2021-02-09 14:49:00.249  WARN 6684 --- [t-dispatcher-85] c.g.k.p.w.actors.TroubleshootingActor    : [TroubleshootingActor] receive DeadLetter: DeadLetter(AskResponse(success=true, data=null, message=null),Actor[akka://oms-server@192.168.64.1:10086/user/server_actor/$d#1810610259],Actor[akka://oms/temp/$xIc])
2021-02-09 14:49:00.380  WARN 6684 --- [8694263193664-1] c.g.k.p.w.c.t.task.CommonTaskTracker     : [TaskTracker-239398694263193664] report finished status failed, result=job success.

java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:91)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:91)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.package$.blocking(package.scala:124)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:91)
	at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.innerRun(CommonTaskTracker.java:240)
	at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.run(CommonTaskTracker.java:306)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

另外接近jvm oom的那段时间，还出现了mysql相关的异常：

2021-02-08 21:04:08.599 [Thread-1853] ERROR o.h.e.j.s.SqlExceptionHelper - HikariPool-1 - Connection is not available, request timed out after 30890ms.
2021-02-08 21:04:08.600 [Thread-1853] ERROR c.g.k.p.s.s.t.s.OmsScheduleService - [CronScheduler] schedule cron job failed.
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:448)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:574)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:361)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy128.save(Unknown Source)
	at com.github.kfcfans.powerjob.server.service.instance.InstanceService.create(InstanceService.java:86)
	at com.github.kfcfans.powerjob.server.service.instance.InstanceService$$FastClassBySpringCGLIB$$5b7fa239.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.github.kfcfans.powerjob.server.service.instance.InstanceService$$EnhancerBySpringCGLIB$$f74bdb37.create(<generated>)
	at com.github.kfcfans.powerjob.server.service.timing.schedule.OmsScheduleService.lambda$null$0(OmsScheduleService.java:139)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.kfcfans.powerjob.server.service.timing.schedule.OmsScheduleService.lambda$scheduleCronJob$4(OmsScheduleService.java:138)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.github.kfcfans.powerjob.server.service.timing.schedule.OmsScheduleService.scheduleCronJob(OmsScheduleService.java:123)
	at com.github.kfcfans.powerjob.server.service.timing.schedule.OmsScheduleService.timingSchedule(OmsScheduleService.java:90)
	at com.github.kfcfans.powerjob.server.service.timing.schedule.OmsScheduleService$$FastClassBySpringCGLIB$$83f6110e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:273)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:281)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246)
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:184)
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:402)
	... 39 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30890ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108)
	... 46 common frames omitted
2021-02-08 21:15:07.096 [Thread-1908] ERROR c.g.k.p.s.s.t.s.OmsScheduleService - [FrequentScheduler] schedule frequent job failed.
org.springframework.dao.InvalidDataAccessApiUsageException: EntityManagerFactory is closed; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:371)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:257)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:154)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy124.findByAppIdInAndStatusAndTimeExpressionTypeIn(Unknown Source)
	at com.github.kfcfans.powerjob.server.service.timing.schedule.OmsScheduleService.lambda$scheduleFrequentJob$11(OmsScheduleService.java:219)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.github.kfcfans.powerjob.server.service.timing.schedule.OmsScheduleService.scheduleFrequentJob(OmsScheduleService.java:216)
	at com.github.kfcfans.powerjob.server.service.timing.schedule.OmsScheduleService.timingSchedule(OmsScheduleService.java:108)
	at com.github.kfcfans.powerjob.server.service.timing.schedule.OmsScheduleService$$FastClassBySpringCGLIB$$83f6110e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.hibernate.internal.SessionFactoryImpl.validateNotClosed(SessionFactoryImpl.java:509)
	at org.hibernate.internal.SessionFactoryImpl.createEntityManager(SessionFactoryImpl.java:588)
	at org.hibernate.internal.SessionFactoryImpl.createEntityManager(SessionFactoryImpl.java:156)
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.invokeProxyMethod(AbstractEntityManagerFactoryBean.java:497)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean$ManagedEntityManagerFactoryInvocationHandler.invoke(AbstractEntityManagerFactoryBean.java:680)
	at com.sun.proxy.$Proxy111.createEntityManager(Unknown Source)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:308)
	at com.sun.proxy.$Proxy115.createQuery(Unknown Source)
	at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.createJpaQuery(AbstractStringBasedJpaQuery.java:156)
	at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.doCreateQuery(AbstractStringBasedJpaQuery.java:86)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.createQuery(AbstractJpaQuery.java:226)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:126)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor$QueryMethodInvoker.invoke(QueryExecutorMethodInterceptor.java:195)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	... 19 common frames omitted

**Comment by KFCFans** [comment]
那问题基本是这样出现的
1. 40个同样配置的任务每次调度和执行结束的时间点都几乎完全一致，这会导致 MySQL 层面有尖刺请求，瞬时写入压力非常大，数据库 overload
2. 数据库 overload 导致 server 的数据库链接池被打满，每个调度请求的处理速度变慢，在某个调度周期内（15S）无法完成一次调度，这个时候**会有新开一个线程进行调度**。
![image](https://user-images.githubusercontent.com/9402086/107328711-1b6dbc00-6aea-11eb-894e-6d95b6f61d67.png)

新开线程调度是不符合预期的，会导致两个问题
1. 重复调度执行问题
2. 重复执行执行导致对数据库的压力进一步扩大
最终导致崩溃。

**Comment by KFCFans** [comment]
结论
1. 正常性能的环境应该不会出现这种问题
2. server 端也需要做一些容灾处理，我后续会把 fixedRate 改为 fixedDelay 来保证只有一个线程进行调度。这样数据库的 overload 只会导致任务 delay，不会导致系统的崩溃。

**Comment by KFCFans** [comment]
有条件的话，你可以加一些对数据库的监控，看看这段时间内数据库的状态如何。
按我估计数据库应该是完全超出负载的状态。

**Comment by KFCFans** [comment]
# 后续 Action

- [ ] 修复多线程调度问题（fixedRate -> fixedDelay）
- [ ] 线程赋予名称，方便排查问题（RejectedExecutionHandlerFactory）
