### ISSUE TITLE
Oracle数据库下主键自增不规律导致Server启动失败

### ISSUE THREAD

**Issue by linwei-scholar** [PowerJob/PowerJob#220]
目前发现使用Oracle数据库(版本19)时，表id自增是不规律的，因为测试任务一直在跑，server_info表只有几条记录，主键id已增加到十万多，Debug时发现MAX_MACHINE_NUM是五位数，所以在启动Serven的时候报错：
`Caused by: java.lang.IllegalArgumentException: machineId can't be greater than MAX_MACHINE_NUM or less than 0
	at com.github.kfcfans.powerjob.server.service.id.SnowFlakeIdGenerator.<init>(SnowFlakeIdGenerator.java:47)
	at com.github.kfcfans.powerjob.server.service.id.IdGenerateService.<init>(IdGenerateService.java:55)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204)`

![image](https://user-images.githubusercontent.com/51738751/108578249-f0426280-735c-11eb-8650-4cba4dbad6e2.png)

**Comment by KFCFans** [comment]
感谢反馈，下版本会解决该问题。目前给出两个临时方案：

1. 手动修改数据库表 ID（比较 hack）
2. 修改 ServerIPProvider 的实现，可以引入 redis 等获取唯一ID
