### ISSUE TITLE
外网部署 server启动akka报异常

### ISSUE THREAD

**Issue by 527826533** [PowerJob/PowerJob#283]
21:02:33.485 [main] INFO tech.powerjob.server.PowerJobServerApplication - 

******************* PowerJob Tips *******************
如果应用无法启动，我们建议您仔细阅读以下文档来解决:
if server can't startup, we recommend that you read the documentation to find a solution:
https://www.yuque.com/powerjob/guidence/problem
******************* PowerJob Tips *******************

21:02:33.537 [main] INFO tech.powerjob.server.remote.transport.starter.AkkaStarter - [PowerJob] PowerJob's akka system start to bootstrap...
21:02:33.564 [main] INFO tech.powerjob.common.utils.NetUtils - [Net] use address from[powerjob.network.local.address]: 121.5.227.131
21:02:33.566 [main] INFO tech.powerjob.server.remote.transport.starter.AkkaStarter - [PowerJob] akka-remote server address: 121.5.227.131:10086
21:02:35.565 [oms-server-akka.actor.default-dispatcher-6] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
21:02:35.802 [oms-server-akka.actor.default-dispatcher-6] WARN akka.remote.RemoteActorRefProvider - Using the 'remote' ActorRefProvider directly, which is a low-level layer. For most use cases, the 'cluster' abstraction on top of remoting is more suitable instead.
21:02:35.803 [oms-server-akka.actor.default-dispatcher-6] WARN akka.remote.RemoteActorRefProvider - Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
21:02:36.089 [oms-server-akka.actor.default-dispatcher-6] ERROR akka.io.TcpListener - Bind failed for TCP channel on endpoint [/121.5.227.131:10086]
java.net.BindException: [/121.5.227.131:10086] Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:60)
	at akka.io.TcpListener.<init>(TcpListener.scala:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:73)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:613)
	at akka.actor.ActorCell.create(ActorCell.scala:640)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

启动server命令： nohup java -Dpowerjob.network.local.address=121.5.227.131 -jar *.jar --spring.profiles.active=product >asset-admin.log&

请教大佬们下我是哪里不对

**Comment by rxxy** [comment]
是不是ip或地址被占用?

**Comment by 527826533** [comment]
> 是不是ip或端口被占用?

不是 就是起不来 你试过外网正常吗

**Comment by rxxy** [comment]
我没试过直接使用外网ip，这个直接暴露在外网不好吧，我猜可能是没有网卡直接绑定了外网ip，可以绑定内网ip做一层转发，ui界面可以通过外网访问，worker通过内网ip和server通信

**Comment by yqyg** [comment]
你好，问题解决了吗？遇到同样问题了

**Comment by KFCFans** [comment]
框架层面考虑到安全性暂时不支持公网，可以通过自行搭建虚拟局域网实现此类调度需求
