### ISSUE TITLE
fatjar方式执行任务报错

### ISSUE THREAD

**Issue by rxxy** [PowerJob/PowerJob#293]
**Describe the bug**
使用fatjar创建容器后，新增并执行任务时报错

任务实例详情
```
任务实例 ID:285189190860144704
状态:失败
运行次数:1
TaskTracker 地址:172.18.0.3:27777
预计执行时间:2021-06-15 23:20:01
开始时间:2021-06-15 23:20:01
结束时间:2021-06-15 23:20:17
节点参数:test
任务实例参数:
任务结果:
NoSuchMethodError: org.apache.commons.io.FileUtils.forceMkdirParent(Ljava/io/File;)V
```

powerjob-server日志
```
- [ProcessorTracker-285189190860144704] create ProcessorTracker failed, all tasks submitted here will fail.
 java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.forceMkdirParent(Ljava/io/File;)V
 	at tech.powerjob.worker.container.OmsContainerFactory.deployContainer(OmsContainerFactory.java:101)
 	at tech.powerjob.worker.container.OmsContainerFactory.fetchContainer(OmsContainerFactory.java:65)
 	at tech.powerjob.worker.core.tracker.processor.ProcessorTracker.initProcessor(ProcessorTracker.java:355)
 	at tech.powerjob.worker.core.tracker.processor.ProcessorTracker.<init>(ProcessorTracker.java:129)
 	at tech.powerjob.worker.actors.ProcessorTrackerActor.lambda$onReceiveTaskTrackerStartTaskReq$1(ProcessorTrackerActor.java:54)
 	at tech.powerjob.worker.core.tracker.processor.ProcessorTrackerPool.getProcessorTracker(ProcessorTrackerPool.java:31)
 	at tech.powerjob.worker.actors.ProcessorTrackerActor.onReceiveTaskTrackerStartTaskReq(ProcessorTrackerActor.java:51)
 	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
 	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
 	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
 	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
 	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
 	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
 	at akka.actor.Actor.aroundReceive(Actor.scala:537)
 	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
 	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
 	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**To Reproduce**
Steps to reproduce the behavior.

https://gitee.com/KFCFans/OhMyScheduler-Container-Template
1. 使用该仓库代码打包后上传
2. 新建外置任务 2#cn.edu.zju.oms.container.SimpleStandaloneProcessor
3. 执行

**Expected behavior**
可以正常执行
**Environment**
 - PowerJob Version: [e.g. 3.0.0]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**
![image](https://user-images.githubusercontent.com/14834156/122081111-69485700-ce31-11eb-9284-6b3d5ff8d208.png)

**Additional context**

**Comment by KFCFans** [comment]
可以看出是 ClassNotFound 的错误，PowerJob 的容器功能依赖 org.apache.commons.io.FileUtils。你的应用应该存在依赖冲突导致运行时不存在这个类。
建议自行解决依赖问题。
tips：powerjob-worker 的 common-io 依赖版本为
```xml
<dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.7</version>
        </dependency>
```
