### ISSUE TITLE
不在同一个局域网，通过jvm启动参数绑定ip,worker端报错

### ISSUE THREAD

**Issue by xiaoxu111** [PowerJob/PowerJob#300]
2021-07-12 11:33:54.286 ERROR 11368 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initPowerJob' defined in class path resource [tech/powerjob/worker/autoconfigure/PowerJobAutoConfiguration.class]: Invocation of init method failed; nested exception is akka.remote.RemoteTransportException: Failed to bind TCP to [106.53.86.136:27777] due to: Bind failed because of java.net.BindException: [/106.53.86.136:27777] Cannot assign requested address: bind
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java:40002) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:41008) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at com.aliwo.UserApplication.main(UserApplication.java:13) [classes/:na]
Caused by: akka.remote.RemoteTransportException: Failed to bind TCP to [106.53.86.136:27777] due to: Bind failed because of java.net.BindException: [/106.53.86.136:27777] Cannot assign requested address: bind
	at akka.remote.artery.tcp.ArteryTcpTransport$$anonfun$4.applyOrElse(ArteryTcpTransport.scala:274) ~[akka-remote_2.13-2.6.12.jar:2.6.12]
	at akka.remote.artery.tcp.ArteryTcpTransport$$anonfun$4.applyOrElse(ArteryTcpTransport.scala:268) ~[akka-remote_2.13-2.6.12.jar:2.6.12]
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:164) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.Promise.complete(Promise.scala:57) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.Promise.complete$(Promise.scala:56) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.Promise.failure(Promise.scala:109) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.Promise.failure$(Promise.scala:109) ~[scala-library-2.13.3.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:104) ~[scala-library-2.13.3.jar:na]
	at akka.stream.impl.io.ConnectionSourceStage$$anon$1.receive(TcpStages.scala:97) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.stream.impl.io.ConnectionSourceStage$$anon$1.$anonfun$preStart$1(TcpStages.scala:68) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.stream.impl.io.ConnectionSourceStage$$anon$1.$anonfun$preStart$1$adapted(TcpStages.scala:68) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.stream.stage.GraphStageLogic$StageActor.internalReceive(GraphStage.scala:242) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$callback$1(GraphStage.scala:201) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$callback$1$adapted(GraphStage.scala:201) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:466) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:498) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:773) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:788) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.actor.Actor.aroundReceive(Actor.scala:537) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.Actor.aroundReceive$(Actor.scala:535) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691) ~[akka-stream_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.invoke(ActorCell.scala:547) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.run(Mailbox.scala:231) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_151]
Caused by: akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anon$2: Bind failed because of java.net.BindException: [/106.53.86.136:27777] Cannot assign requested address: bind
Caused by: java.net.BindException: [/106.53.86.136:27777] Cannot assign requested address: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_151]
	at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_151]
	at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_151]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_151]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_151]
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:60) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.io.TcpListener.<init>(TcpListener.scala:57) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_151]
	at akka.util.Reflect$.instantiate(Reflect.scala:73) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.Props.newActor(Props.scala:226) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.newActor(ActorCell.scala:613) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.create(ActorCell.scala:640) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.run(Mailbox.scala:230) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) ~[akka-actor_2.13-2.6.12.jar:2.6.12]
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_151]

**Comment by yqyg** [comment]
你好，问题解决了吗？遇到同样问题了

**Comment by abadfox233** [comment]
powerjob 的分布式依赖 AkkA ，而 powerjob 内并没有使用 AKKA的NAT功能，所以跨区域网时powerjob的server并不能连接worker。想解决这个问题需要修改源代码，具体可以参考 https://doc.akka.io/docs/akka/current/remoting-artery.html。 
我改了一些代码，可以参考这个仓库 https://gitee.com/a_bad_fox/PowerJob
