### ISSUE TITLE
执行器宕机

### ISSUE THREAD

**Issue by Aaronqs** [PowerJob/PowerJob#311]
执行器执行一段时间后宕机
[2021-07-27 00:11:08] [ctttp-300059945036939456-1] [INFO] [com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable:256] [TaskTracker-300059945036939456] instance process finished,result = release resour
ce success, start to release resource...
[2021-07-27 00:11:08] [oms-akka.processor-tracker-dispatcher-253] [INFO] [com.github.kfcfans.powerjob.worker.core.tracker.processor.ProcessorTracker:186] [ProcessorTracker-300059945036939456] ProcessorTracker destroyed successfully!
[2021-07-27 00:11:08] [ctttp-300059945036939456-1] [INFO] [com.github.kfcfans.powerjob.worker.core.tracker.task.TaskTracker:356] [TaskTracker-300059945036939456] TaskTracker has left the world(using 318.2 μs), bye~
[2021-07-27 00:11:14] [ctttp-300059860467187904-0] [INFO] [com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable:256] [TaskTracker-300059860467187904] instance process finished,result = process succes
s, start to release resource...
[2021-07-27 00:11:14] [oms-akka.processor-tracker-dispatcher-253] [INFO] [com.github.kfcfans.powerjob.worker.core.tracker.processor.ProcessorTracker:186] [ProcessorTracker-300059860467187904] ProcessorTracker destroyed successfully!
[2021-07-27 00:11:14] [ctttp-300059860467187904-0] [INFO] [com.github.kfcfans.powerjob.worker.core.tracker.task.TaskTracker:356] [TaskTracker-300059860467187904] TaskTracker has left the world(using 2.145 ms), bye~
[2021-07-27 00:30:19] [SpringContextShutdownHook] [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] Shutting down ExecutorService 'taskScheduler'
[2021-07-27 00:30:19] [oms-akka.actor.default-dispatcher-269] [WARN] [akka.event.slf4j.Slf4jLogger$$anonfun$receive$1:89] Could not addJvmShutdownHook, due to: Shutdown in progress
[2021-07-27 00:30:19] [SpringContextShutdownHook] [INFO] [org.springframework.orm.jpa.AbstractEntityManagerFactoryBean:598] Closing JPA EntityManagerFactory for persistence unit 'default'
[2021-07-27 00:30:19] [oms-akka.actor.default-dispatcher-269] [WARN] [akka.event.slf4j.Slf4jLogger$$anonfun$receive$1:89] [outbound connection to [akka://oms-server@**.**.***.*:10086], control stream] Upstream failed, cause: StreamTcpExc
eption: The connection has been aborted
[2021-07-27 00:30:19] [oms-akka.actor.default-dispatcher-269] [WARN] [akka.event.slf4j.Slf4jLogger$$anonfun$receive$1:89] [outbound connection to [akka://oms-server@**.**.***.*:10086], message stream] Upstream failed, cause: StreamTcpExc
eption: The connection has been aborted
[2021-07-27 00:30:19] [SpringContextShutdownHook] [INFO] [com.zaxxer.hikari.HikariDataSource:350] HikariPool-1 - Shutdown initiated...
[2021-07-27 00:30:19] [SpringContextShutdownHook] [INFO] [com.zaxxer.hikari.HikariDataSource:352] HikariPool-1 - Shutdown completed.
[2021-07-27 00:30:19] [SpringContextShutdownHook] [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] Shutting down ExecutorService
再次启动执行器报错
[2021-07-27 09:19:49] [ctttp-300198002331484352-1] [WARN] [com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable:243] [TaskTracker-300198002331484352] report finished status failed, result=release res
ource success.
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
        at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:91)
        at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:91)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
        at scala.concurrent.package$.blocking(package.scala:124)
        at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:91)
        at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.innerRun(CommonTaskTracker.java:240)
        at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.run(CommonTaskTracker.java:306)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
此时需要重启server

**Comment by KFCFans** [comment]
再次出现的时候可以提供下线程和内存的 dump 文件，方便排查。
