### ISSUE TITLE
akka woker上报任务状态server出现大量超时失败

### ISSUE THREAD

**Issue by 18846837414** [PowerJob/PowerJob#432]
版本：3.4.5
woker通过akka ask上报任务状态server时出现大量超时失败，然后就是报DeadLetter；
不清楚啥时候报的，随着接入的业务越来越多，报的越来越多
server woker均跑在k8s里,从监控上看资源都非常充足。
server日志无异常
woker部分日志：
2022-07-13 18:12:08 |WARN |ctttp-427530013412166985-1 |c.g.k.p.w.c.t.t.CommonTaskTracker |[TaskTracker-427530013412166985] report finished status failed, result=code:200,body:true.
java.util.concurrent.TimeoutException: null
at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:91)
at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:91)
at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
at scala.concurrent.package$.blocking(package.scala:124)
at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:91)
at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.innerRun(CommonTaskTracker.java:240)
at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.run(CommonTaskTracker.java:306)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2022-07-13 18:12:08 |WARN |oms-akka.actor.default-dispatcher-4289 |c.g.k.p.w.a.TroubleshootingActor |[TroubleshootingActor] receive DeadLetter: DeadLetter(AskResponse(success=true, data=null, message=null),Actor[akka://oms-server@10.235.213.210:10086/user/server_actor/$E#1638613515],Actor[akka://oms/temp/$Zoke])
2022-07-13 18:12:08 |WARN |ctttp-427530013412167000-1 |c.g.k.p.w.c.t.t.CommonTaskTracker |[TaskTracker-427530013412167000] report finished status failed, result=code:200,body:true.
java.util.concurrent.TimeoutException: null
at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:91)
at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:91)
at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
at scala.concurrent.package$.blocking(package.scala:124)
at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:91)
at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.innerRun(CommonTaskTracker.java:240)
at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.run(CommonTaskTracker.java:306)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2022-07-13 18:12:08 |WARN |oms-akka.actor.default-dispatcher-4289 |c.g.k.p.w.a.TroubleshootingActor |[TroubleshootingActor] receive DeadLetter: DeadLetter(AskResponse(success=true, data=null, message=null),Actor[akka://oms-server@10.235.213.210:10086/user/server_actor/$l#-814262510],Actor[akka://oms/temp/$4oke])
2022-07-13 18:12:08 |WARN |oms-akka.actor.default-dispatcher-88 |c.g.k.p.w.a.TroubleshootingActor |[TroubleshootingActor] receive DeadLetter: DeadLetter(AskResponse(success=true, data=null, message=null),Actor[akka://oms-server@10.235.213.210:10086/user/server_actor/$F#-1983198792],Actor[akka://oms/temp/$0oke])

@KFCFans @Echo009

**Comment by starchen-jnu** [comment]
我同样出现这种问题，资源充足，1000个任务执行，都撑不住了，调度超时，没有可用的worker,但有些worker都没有用到，任务重复执行。感觉这框架现在缺乏维护了，我现在都考虑要换框架了，要不然业务量多了，撑不住啊

**Comment by 18846837414** [comment]
你的一千个是同时执行吗，一千个应该还是很轻松的，没有可用的worker这个你可以稍微排查一下，我估计跟woker上报状态超时有关；
关于有些worker都没有用到，他是根据你woker上报健康状态来派发的，同时并发就可能都打到一个点上面了，加上如果你的服务都是跑在容器里面的，他那个取健康度这个是不太正确的，你要不就直接给任务取模来做，大并发下就负载均衡了；
任务重复执行应该是Akka通信丢失，导致一些任务状态没修改，所以进行了重复派发；akka这个我看了很多文档说通信1s能好几W,，按道理是很成熟的框架，不知道为啥嗷嗷报失败，不知道是不是容器环境的原因，很愁；
我估计把akka通信失败这个问题解决了，这些问题全都解决了@starchen-jnu

**Comment by starchen-jnu** [comment]
> 你的一千个是同时执行吗，一千个应该还是很轻松的，没有可用的worker这个你可以稍微排查一下，我估计跟woker上报状态超时有关； 关于有些worker都没有用到，他是根据你woker上报健康状态来派发的，同时并发就可能都打到一个点上面了，加上如果你的服务都是跑在容器里面的，他那个取健康度这个是不太正确的，你要不就直接给任务取模来做，大并发下就负载均衡了； 任务重复执行应该是Akka通信丢失，导致一些任务状态没修改，所以进行了重复派发；akka这个我看了很多文档说通信1s能好几W,，按道理是很成熟的框架，不知道为啥嗷嗷报失败，不知道是不是容器环境的原因，很愁； 我估计把akka通信失败这个问题解决了，这些问题全都解决了@starchen-jnu

我也是部署在容器里。。。它有两种通信模式，随机选择worker模式也试过了，压测还是会出现这种问题。感觉调度worker的处理能力不行，任务多，处理不过来，但扩充了worker数量，却没有负载均衡到各worker节上。按道理是不应该会出现这种问题，worker水平扩展没起作用。愁。。。

**Comment by Echo009** [comment]
看下数据库的响应时间是否正常，如果正常，应该是分段锁冲突导致的非必要阻塞，继而导致 Worker 端的请求超时。
如果比较急，可以 cherry-pick 一下这个提交，看下能否解决
https://github.com/Echo009/PowerJob/commit/abbef2bdbe2cdc0fcfd9bc9d43205d9857a1720f

**Comment by Echo009** [comment]
看下数据库的响应时间是否正常，如果正常，应该是分段锁冲突导致的非必要阻塞，继而导致 Worker 端的请求超时。
如果比较急，可以 cherry-pick 一下这个提交，看下能否解决
https://github.com/Echo009/PowerJob/commit/abbef2bdbe2cdc0fcfd9bc9d43205d9857a1720f

**Comment by 18846837414** [comment]
> 看下数据库的响应时间是否正常，如果正常，应该是分段锁冲突导致的非必要阻塞，继而导致 Worker 端的请求超时。 如果比较急，可以 cherry-pick 一下这个提交，看下能否解决 [Echo009@abbef2b](https://github.com/Echo009/PowerJob/commit/abbef2bdbe2cdc0fcfd9bc9d43205d9857a1720f)

没太懂。。。。，如果分段锁引起的冲突，那么在派发任务到woker这段时间就开始报通信异常了才对，但是我这个异常是已经执行完毕最终阶段状态上报给sever的时候报的，且都是这个ask超时

**Comment by 18846837414** [comment]
> 看下数据库的响应时间是否正常，如果正常，应该是分段锁冲突导致的非必要阻塞，继而导致 Worker 端的请求超时。 如果比较急，可以 cherry-pick 一下这个提交，看下能否解决 [Echo009@abbef2b](https://github.com/Echo009/PowerJob/commit/abbef2bdbe2cdc0fcfd9bc9d43205d9857a1720f)

没太懂。。。。，如果分段锁引起的冲突，那么是不是应该在派发任务到woker这段时间就开始报通信异常了才对，但是我这个异常是已经执行完毕最终阶段状态上报给sever的时候报的，且都是只有这个ask超时相同的异常

**Comment by Echo009** [comment]
> > 看下数据库的响应时间是否正常，如果正常，应该是分段锁冲突导致的非必要阻塞，继而导致 Worker 端的请求超时。 如果比较急，可以 cherry-pick 一下这个提交，看下能否解决 [Echo009@abbef2b](https://github.com/Echo009/PowerJob/commit/abbef2bdbe2cdc0fcfd9bc9d43205d9857a1720f)
> 
> 没太懂。。。。，如果分段锁引起的冲突，那么是不是应该在派发任务到woker这段时间就开始报通信异常了才对，但是我这个异常是已经执行完毕最终阶段状态上报给sever的时候报的，且都是只有这个ask超时相同的异常

报这个错误的场景是单个任务还是工作流中的任务？如果是后者那么是有有可能是因为分段锁冲突导致。另外看下出现错误的时候 server 端各个 akka dispatcher 线程栈信息

**Comment by KFCFans** [comment]
@18846837414 可以先按 echo 说的，dump 下 server 的线程栈，然后看看卡在哪里。
从你给出的堆栈看，timeout 是从上报执行状态这边发出的。而 server 处理结果其实只是做了写 DB 操作，所以大概率可能是触发了 DB 的性能瓶颈，你可以看下 DB 相关的监控确认下。有问题可以再反馈。

@Echo009 目前感觉 PowerJob 的监控还是比较弱（好吧，其实是0），后面找时间可以一起聊一个监控方案，至少做到系统自身的核心 API 的日志埋点，比如核心方法的平均 rt、调度的平均延迟、调度量等等，然后给出一个简单的日志、监控采集和部署方案（比如 ELK）

**Comment by KFCFans** [comment]
@18846837414 还有目前初步怀疑可能是接入的用户中存在大量上报 omsLogger 日志导致 server 端被打爆的情况，这块也可以线程 dump 看看，server 的瓶颈卡在哪里

**Comment by andychyiyi** [comment]
V4.0.1 This problem. I don't know whether the subsequent versions have been repaired
