### ISSUE TITLE
本地项目启动报H2数据库创建表task_info失败 

### ISSUE THREAD

**Issue by WayneTao13** [PowerJob/PowerJob#436]
错误日志
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initPowerJobWorker' defined in class path resource [com/njlgkj/management/config/PowerJobWorkerConfiguration.class]: 
Invocation of init method failed; nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table task_info (task_id varchar(255), instance_id bigint[*](20), sub_instance_id bigint(20), task_name varchar(255), task_content blob, address varchar(255), status int(5), result text, failed_cnt int(11), created_time bigint(20), last_modified_time bigint(20), last_report_time bigint(20), unique KEY pkey (instance_id, task_id))"; expected "ARRAY, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, DEFAULT, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
create table task_info (task_id varchar(255), instance_id bigint(20), sub_instance_id bigint(20), task_name varchar(255), task_content blob, address varchar(255), status int(5), result text, failed_cnt int(11), created_time bigint(20), last_modified_time bigint(20), last_report_time bigint(20), unique KEY pkey (instance_id, task_id)) [42001-212]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.0.jar:2.7.0]
	at com.njlgkj.management.ManagementApplication.main(ManagementApplication.java:11) ~[classes/:?]`

Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table task_info (task_id varchar(255), instance_id bigint[*](20), sub_instance_id bigint(20), task_name varchar(255), task_content blob, address varchar(255), status int(5), result text, failed_cnt int(11), created_time bigint(20), last_modified_time bigint(20), last_report_time bigint(20), unique KEY pkey (instance_id, task_id))"; expected "ARRAY, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, DEFAULT, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
create table task_info (task_id varchar(255), instance_id bigint(20), sub_instance_id bigint(20), task_name varchar(255), task_content blob, address varchar(255), status int(5), result text, failed_cnt int(11), created_time bigint(20), last_modified_time bigint(20), last_report_time bigint(20), unique KEY pkey (instance_id, task_id)) [42001-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.message.DbException.getSyntaxError(DbException.java:261) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.getSyntaxError(Parser.java:907) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.read(Parser.java:5743) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.readIfMore(Parser.java:1276) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parseCreateTable(Parser.java:9267) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parseCreate(Parser.java:6745) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parsePrepared(Parser.java:763) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parse(Parser.java:691) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parse(Parser.java:666) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.prepareCommand(Parser.java:568) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:237) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223) ~[h2-2.1.212.jar:2.1.212]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar:?]
	at tech.powerjob.worker.persistence.TaskDAOImpl.initTable(TaskDAOImpl.java:35) ~[powerjob-worker-4.0.1.jar:4.0.1]
	at tech.powerjob.worker.persistence.TaskPersistenceService.init(TaskPersistenceService.java:48) ~[powerjob-worker-4.0.1.jar:4.0.1]
	at tech.powerjob.worker.PowerJobWorker.init(PowerJobWorker.java:140) ~[powerjob-worker-4.0.1.jar:4.0.1]
	at tech.powerjob.worker.PowerJobWorker.afterPropertiesSet(PowerJobWorker.java:67) ~[powerjob-worker-4.0.1.jar:4.0.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.20.jar:5.3.20]
	... 16 more
2022-08-08 16:52:54.152  INFO 22872 --- [           main] t.p.w.p.ConnectionFactory  : [PowerDatasource] init h2 datasource successfully, use url: jdbc:h2:file:C:\Users\Administrator/powerjob/worker/h2/5e1a9db953ff4dff92c8fc1205fc5ceb/powerjob_worker_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
2022-08-08 17:18:06.040  WARN 22872 --- [l-1 housekeeper] c.z.h.p.HikariPool : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=25m41s887ms301µs500ns).
2022-08-08 17:18:06.043 ERROR 22872 --- [           main] t.p.w.PowerJobWorker : [PowerJobWorker] initialize PowerJobWorker failed, using 25.24 min.
```

**Comment by WayneTao13** [comment]
`2022-08-08 16:52:54.152  INFO 22872 --- [           main] t.p.w.p.ConnectionFactory                : [PowerDatasource] init h2 datasource successfully, use url: jdbc:h2:file:C:\Users\Administrator/powerjob/worker/h2/5e1a9db953ff4dff92c8fc1205fc5ceb/powerjob_worker_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
2022-08-08 17:18:06.040  WARN 22872 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=25m41s887ms301µs500ns).
2022-08-08 17:18:06.043 ERROR 22872 --- [           main] t.p.w.PowerJobWorker                     : [PowerJobWorker] initialize PowerJobWorker failed, using 25.24 min.`

**Comment by WayneTao13** [comment]
debug了下跟语句里表名task_info没关系跟里面字段有关系

**Comment by WayneTao13** [comment]
Syntax error in SQL statement "create table task_info (task_id varchar(255), instance_id bigint[*](20), sub_instance_id bigint(20), task_name varchar(255), task_content blob, address varchar(255), status int(5), result text, failed_cnt int(11), created_time bigint(20), last_modified_time bigint(20), last_report_time bigint(20), unique KEY pkey (instance_id, task_id))"; expected "ARRAY, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, DEFAULT, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
create table task_info (task_id varchar(255), instance_id bigint(20), sub_instance_id bigint(20), task_name varchar(255), task_content blob, address varchar(255), status int(5), result text, failed_cnt int(11), created_time bigint(20), last_modified_time bigint(20), last_report_time bigint(20), unique KEY pkey (instance_id, task_id)) [42001-212]

**Comment by WayneTao13** [comment]
"create table task_info (task_id varchar(255))"这个语句没问题
"create table task_info (instance_id bigint(20))"有bigint就报错

**Comment by WayneTao13** [comment]
我用源码的worker-samples启动就没问题，猜测是项目依赖有问题？

**Comment by WayneTao13** [comment]
实测跟springboot版本有关系，替换项目springboot版本2.6.6跟2.6.10都没问题
