### ISSUE TITLE
程序启动worker，并且使用BasicProcessor时，报错

### ISSUE THREAD

**Issue by bxcxnn** [PowerJob/PowerJob#496]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by bxcxnn** [comment]
10:46:59.224 [oms-akka.processor-tracker-dispatcher-46] WARN  tech.powerjob.worker.core.tracker.processor.ProcessorTracker - [ProcessorTracker-481413904669343872] no spring bean of processor(className=tech.powerjob.samples.processors.SimpleProcessor), reason is ClassNotFoundException: tech.powerjob.samples.processors.SimpleProcessor.
10:46:59.226 [oms-akka.processor-tracker-dispatcher-46] WARN  tech.powerjob.worker.core.ProcessorBeanFactory - [ProcessorBeanFactory] load local Processor(className = tech.powerjob.samples.processors.SimpleProcessor) failed.
java.lang.ClassNotFoundException: tech.powerjob.samples.processors.SimpleProcessor
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:315) ~[?:?]
	at tech.powerjob.worker.core.ProcessorBeanFactory.lambda$getLocalProcessor$0(ProcessorBeanFactory.java:37) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
	at tech.powerjob.worker.core.ProcessorBeanFactory.getLocalProcessor(ProcessorBeanFactory.java:34) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at tech.powerjob.worker.core.tracker.processor.ProcessorTracker.initProcessor(ProcessorTracker.java:349) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at tech.powerjob.worker.core.tracker.processor.ProcessorTracker.<init>(ProcessorTracker.java:132) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at tech.powerjob.worker.actors.ProcessorTrackerActor.lambda$onReceiveTaskTrackerStartTaskReq$1(ProcessorTrackerActor.java:54) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at tech.powerjob.worker.core.tracker.processor.ProcessorTrackerPool.getProcessorTracker(ProcessorTrackerPool.java:31) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at tech.powerjob.worker.actors.ProcessorTrackerActor.onReceiveTaskTrackerStartTaskReq(ProcessorTrackerActor.java:51) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187) [scala-library-2.13.3.jar:?]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186) [scala-library-2.13.3.jar:?]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241) [scala-library-2.13.3.jar:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:537) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.Actor.aroundReceive$(Actor.scala:535) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.receiveMessage$$$capture(ActorCell.scala:577) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.invoke(ActorCell.scala:547) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.run(Mailbox.scala:231) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
10:46:59.232 [oms-akka.processor-tracker-dispatcher-46] WARN  tech.powerjob.worker.core.tracker.processor.ProcessorTracker - [ProcessorTracker-481413904669343872] create ProcessorTracker failed, all tasks submitted here will fail.

**Comment by bxcxnn** [comment]
10:46:59.224 [oms-akka.processor-tracker-dispatcher-46] WARN  tech.powerjob.worker.core.tracker.processor.ProcessorTracker - [ProcessorTracker-481413904669343872] no spring bean of processor(className=tech.powerjob.samples.processors.SimpleProcessor), reason is ClassNotFoundException: tech.powerjob.samples.processors.SimpleProcessor.
10:46:59.226 [oms-akka.processor-tracker-dispatcher-46] WARN  tech.powerjob.worker.core.ProcessorBeanFactory - [ProcessorBeanFactory] load local Processor(className = tech.powerjob.samples.processors.SimpleProcessor) failed.
java.lang.ClassNotFoundException: tech.powerjob.samples.processors.SimpleProcessor
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:315) ~[?:?]
	at tech.powerjob.worker.core.ProcessorBeanFactory.lambda$getLocalProcessor$0(ProcessorBeanFactory.java:37) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
	at tech.powerjob.worker.core.ProcessorBeanFactory.getLocalProcessor(ProcessorBeanFactory.java:34) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at tech.powerjob.worker.core.tracker.processor.ProcessorTracker.initProcessor(ProcessorTracker.java:349) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at tech.powerjob.worker.core.tracker.processor.ProcessorTracker.<init>(ProcessorTracker.java:132) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at tech.powerjob.worker.actors.ProcessorTrackerActor.lambda$onReceiveTaskTrackerStartTaskReq$1(ProcessorTrackerActor.java:54) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at tech.powerjob.worker.core.tracker.processor.ProcessorTrackerPool.getProcessorTracker(ProcessorTrackerPool.java:31) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at tech.powerjob.worker.actors.ProcessorTrackerActor.onReceiveTaskTrackerStartTaskReq(ProcessorTrackerActor.java:51) ~[powerjob-worker-4.2.0.jar:4.2.0]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187) [scala-library-2.13.3.jar:?]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186) [scala-library-2.13.3.jar:?]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241) [scala-library-2.13.3.jar:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:537) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.Actor.aroundReceive$(Actor.scala:535) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.receiveMessage$$$capture(ActorCell.scala:577) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.actor.ActorCell.invoke(ActorCell.scala:547) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.run(Mailbox.scala:231) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [akka-actor_2.13-2.6.12.jar:2.6.12]
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
10:46:59.232 [oms-akka.processor-tracker-dispatcher-46] WARN  tech.powerjob.worker.core.tracker.processor.ProcessorTracker - [ProcessorTracker-481413904669343872] create ProcessorTracker failed, all tasks submitted here will fail.
