### ISSUE TITLE
执行时报错，报找不到worker，但是实际上是管理页面上是由在现代的worker的，ps:执行器和service不在一个服务上

### ISSUE THREAD

**Issue by liva-ohc** [PowerJob/PowerJob#498]
2022-12-09 17:17:20.464  WARN 1 --- [r-dispatcher-85] t.p.w.c.t.processor.ProcessorTracker     : [ProcessorTracker-481512117418066240] create ProcessorTracker failed, all tasks submitted here will fail.
java.lang.ClassNotFoundException: com.XXX.system.actuator.timer.PowerJobMapReduceTimer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at tech.powerjob.worker.core.ProcessorBeanFactory.lambda$getLocalProcessor$0(ProcessorBeanFactory.java:37)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at tech.powerjob.worker.core.ProcessorBeanFactory.getLocalProcessor(ProcessorBeanFactory.java:34)
	at tech.powerjob.worker.core.tracker.processor.ProcessorTracker.initProcessor(ProcessorTracker.java:346)
	at tech.powerjob.worker.core.tracker.processor.ProcessorTracker.<init>(ProcessorTracker.java:129)
	at tech.powerjob.worker.actors.ProcessorTrackerActor.lambda$onReceiveTaskTrackerStartTaskReq$1(ProcessorTrackerActor.java:54)
	at tech.powerjob.worker.core.tracker.processor.ProcessorTrackerPool.getProcessorTracker(ProcessorTrackerPool.java:31)
	at tech.powerjob.worker.actors.ProcessorTrackerActor.onReceiveTaskTrackerStartTaskReq(ProcessorTrackerActor.java:51)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by Echo009** [comment]
![image](https://user-images.githubusercontent.com/24402043/206685216-93812dc5-db02-42de-8d40-b3d15960a745.png)

这个错误提示已经很明显了，先检查下 worker 上有没有这个类

**Comment by liva-ohc** [comment]
嗯嗯，是因为worker的服务启动了多台导致的
