### ISSUE TITLE
加了-Dpowerjob.network.local.address后docker服务起不来

### ISSUE THREAD

**Issue by WyoungIT** [PowerJob/PowerJob#507]
## Question
加了-Dpowerjob.network.local.address后docker服务起不来，报错如下

Caused by: akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anon$2: Bind failed because of java.net.BindException: [/XXX:10086] Cannot assign requested address
Caused by: java.net.BindException: [/XXX:10086] Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:438)
	at sun.nio.ch.Net.bind(Net.java:430)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:225)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:60)
	at akka.io.TcpListener.<init>(TcpListener.scala:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:73)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:613)
	at akka.actor.ActorCell.create(ActorCell.scala:640)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)

### ### 启动命令
docker run -d \
	--restart=always \
       --name powerjob-server \
       -p 7700:7700 -p 10086:10086 \
       -e TZ="Asia/Shanghai" \
       -e JVMOPTIONS="-Dpowerjob.network.local.address=云服务器外网IP" \
       -e PARAMS="--spring.profiles.active=product --spring.datasource.core.jdbc-url=jdbc:mysql://XXX:3306/powerjob-product?useUnicode=true&characterEncoding=UTF-8 --spring.datasource.core.username=XX --spring.datasource.core.password=XX --spring.data.mongodb.uri=mongodb://XX:XX@127.0.0.1:27017/powerjob-product" \
       -v /data2/powerjob/server:/root/powerjob/server -v /data2/.m2:/root/.m2 \
       tjqq/powerjob-server:latest;

**Comment by WyoungIT** [comment]
这个问题一直有人遇到吧，一直不解决嘞

**Comment by Echo009** [comment]
能用 `-Dpowerjob.network.local.address`  绑定 ip 的前提是你指定的这个 ip 是合法的。

在 docker 中跑，默认用的是 bridge 模式，会有自己的网络命名空间，在容器内可见的都是虚拟出来的网卡，宿主机的这个 ip （你提到的云服务器外网 ip） 在容器内肯定是不可见的。

最简单的解决方案就是给 docker 命令加上 `--net=host` 参数，用 host 模式运行 。

另外建议不要将 server 暴露在外网，现在 worker 和 server 之间没有任何认证机制。

**Comment by WyoungIT** [comment]
这个有后续规划吗？网络模块升级，10086端口制定公网ip+认证机制。

**Comment by Echo009** [comment]
> 这个有后续规划吗？网络模块升级，10086端口制定公网ip+认证机制。
> 
> https://doc.akka.io/docs/akka/current/remoting-artery.html

暂无升级 akka 的计划，后续会替换协议层的实现
