### ISSUE TITLE
有没有考虑迭代JDK17+

### ISSUE THREAD

**Issue by ChrysanSun** [PowerJob/PowerJob#529]
springboot3.0+

**Comment by KFCFans** [comment]
分2部分：
1. 可用性方面，PowerJob 会及时修复任何高版本 JDK 遇到的问题，保证在高版本环境上可运行
2. 项目主框架上，可能会在 JDK21 发布的节点切到 5.0 ，基于 JDK21 和 SpringBoot3 开发。同时维护一段时间的 4.x 版本。不过这个具体节奏要看 JDK 和 SpringBoot 的成熟度和升级收益。

**Comment by ylq5126** [comment]
> 分2部分：
> 
> 1. 可用性方面，PowerJob 会及时修复任何高版本 JDK 遇到的问题，保证在高版本环境上可运行
> 2. 项目主框架上，可能会在 JDK21 发布的节点切到 5.0 ，基于 JDK21 和 SpringBoot3 开发。同时维护一段时间的 4.x 版本。不过这个具体节奏要看 JDK 和 SpringBoot 的成熟度和升级收益。

源码使用jdk17编译后无法启动
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

**Comment by ylq5126** [comment]
使用jdk17 项目无法运行

**Comment by KFCFans** [comment]
> 使用jdk17 项目无法运行

把相关的错误信息贴出来，反馈到 GitHub，官方会进行修复和兼容

**Comment by KFCFans** [comment]
worker 在JDK17测试通过，如果是 samples 项目起不来，可以加入以下依赖
```
<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
 </dependency>
```

**Comment by ylq5126** [comment]
server 暂不考虑jdk17 么？

**Comment by ylq5126** [comment]
> worker 在JDK17测试通过，如果是 samples 项目起不来，可以加入以下依赖
> 
> ```
> <dependency>
>             <groupId>javax.xml.bind</groupId>
>             <artifactId>jaxb-api</artifactId>
>             <version>2.3.1</version>
>  </dependency>
> ```

主要是server 端，因为部署的环境不能访问Internet

**Comment by ylq5126** [comment]
4.3.0版本在用jdk8编译，需要添加jaxb，能正常运行

**Comment by AmbitionLover** [comment]
Caused by: java.lang.ClassNotFoundException: javax.websocket.server.ServerEndpointConfig$Configurator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)


springbooot3. : 3.1.1.  server 启动 运行报错
