### ISSUE TITLE
是否存在参数配置开启或者关闭powerjob

### ISSUE THREAD

**Issue by honghao12** [PowerJob/PowerJob#536]
在某些环境下不需要powerjob，能否通过配置参数关闭powerjob, 以便启动项目时不会报错找不到server
```
tech.powerjob.common.exception.PowerJobException: no server available!
	at tech.powerjob.worker.PowerJobWorker.assertAppName(PowerJobWorker.java:188)
	at tech.powerjob.worker.PowerJobWorker.init(PowerJobWorker.java:87)
	at tech.powerjob.worker.PowerJobWorker.afterPropertiesSet(PowerJobWorker.java:67)
```

**Comment by honghao12** [comment]
已找到参数配置

**Comment by Echo009** [comment]
如果是用 powerjob-worker-springboot-starter 方式接入的可通过添加配置 `powerjob.worker.enabled=false` 来关闭。
其他情况下，可以通过添加配置 `powerjob.worker.enableTestMode=true` 来开启测试模式，启动时就不会报错
