### ISSUE TITLE
使用官方处理器报错

### ISSUE THREAD

**Issue by xiuFranklin** [PowerJob/PowerJob#550]
`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'tech.powerjob.official.processors.impl.script.ShellProcessor' available
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:354)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:345)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1126)
        at tech.powerjob.worker.processor.impl.BuiltInSpringProcessorFactory.getBean(BuiltInSpringProcessorFactory.java:70)
        at tech.powerjob.worker.processor.impl.BuiltInSpringProcessorFactory.build(BuiltInSpringProcessorFactory.java:44)
        at tech.powerjob.worker.processor.PowerJobProcessorLoader.lambda$load$0(PowerJobProcessorLoader.java:44)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at tech.powerjob.worker.processor.PowerJobProcessorLoader.load(PowerJobProcessorLoader.java:33)
        at tech.powerjob.worker.core.tracker.task.light.LightTaskTracker.<init>(LightTaskTracker.java:90)
        at tech.powerjob.worker.core.tracker.task.light.LightTaskTracker.create(LightTaskTracker.java:126)
        at tech.powerjob.worker.actors.TaskTrackerActor.lambda$onReceiveServerScheduleJobReq$1(TaskTrackerActor.java:142)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at tech.powerjob.worker.core.tracker.manager.LightTaskTrackerManager.atomicCreateTaskTracker(LightTaskTrackerManager.java:32)
        at tech.powerjob.worker.actors.TaskTrackerActor.onReceiveServerScheduleJobReq(TaskTrackerActor.java:142)
        at tech.powerjob.worker.actors.WorkerActor.onReceiveServerScheduleJobReq(WorkerActor.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at tech.powerjob.remote.akka.AkkaProxyActor.onReceiveProcessorReportTaskStatusReq(AkkaProxyActor.java:56)
        at tech.powerjob.remote.akka.AkkaProxyActor.lambda$null$0(AkkaProxyActor.java:43)
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:214)
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:213)
        at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:269)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)`

**Comment by KFCFans** [comment]
注意日志级别，这应该只是个 warning，且后续不会出现。

**Comment by xiuFranklin** [comment]
解决方案是，将官方处理器注册到bean里面，这样springboot就不会报找不到官方处理器的错误。解决示例代码如下：
`@Configuration
public class PowerJobConfig {

    @Bean
    public ShellProcessor shellInit() {

        return new ShellProcessor();
    }

    @Bean
    public PythonProcessor pythonInit() {

        return new PythonProcessor();
    }

    @Bean
    public HttpProcessor httpInit() {

        return new HttpProcessor();
    }`
