### ISSUE TITLE
【BUG】4.3.0版本 swagger-ui 启动报错

### ISSUE THREAD

**Issue by PyraAryp** [PowerJob/PowerJob#559]
使用docker启动powerjob-server异常

**Comment by PyraAryp** [comment]
如果我在docker命令行添加`--oms.swagger.enable=true`,例如：


    docker run -d --restart=always \
            --name powerjob-server \
            -p 7700:7700 -p 10086:10086 \
            -e TZ="Asia/Shanghai" \
            -e JVMOPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=10000 -Dcom.sun.management.jmxremote.rmi.port=10000 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false" \
            -e PARAMS="--oms.swagger.enable=true --spring.profiles.active=product --spring.datasource.core.jdbc-url=jdbc:mysql://XXXXX:3306/powerjob?useUnicode=true&characterEncoding=UTF-8 --spring.datasource.core.username=root --spring.datasource.core.password=XXXXXX --spring.data.mongodb.uri=mongodb://XXXXX:27017/powerjob" \
            -v ~/docker/powerjob-server:/root/powerjob/server \
            -v ~/.m2:/root/.m2 \
            tjqq/powerjob-server:4.3.0


则会报下面的错误


      Exception in thread "Thread-8" org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'omsRemoteDatasource': Could not bind properties to 'DataSource' : prefix=spring.datasource.core, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@13d73f29 has not been refreshed yet
              at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:92)
              at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:78)
              at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
              at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
              at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
              at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
              at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
              at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
              at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
              at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
              at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
              at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
              at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
              at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
              at org.springframework.beans.factory.support.ConstructorResolver.resolvePreparedArguments(ConstructorResolver.java:834)
              at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:449)
              at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
              at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
              at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
              at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
              at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
              at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
              at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)

去掉则可以正常启动.

**Comment by KFCFans** [comment]
应该是不小心动到了其他参数导致的吧？
你可以自己看源码，这一行配置不会影响到数据库连接层。可以说毫不相关。

**Comment by PyraAryp** [comment]
并没有修改参数呀，主要就是增加了 `--oms.swagger.enable=true`

然后我重新部署了一遍，同时将版本改到4.2.1版本

    docker run -d  --restart=always \
            --name powerjob-server \
            -p 7700:7700 -p 10086:10086 \
            -e TZ="Asia/Shanghai" \
            -e PARAMS="--spring.profiles.active=product \
            --oms.swagger.enable=true \
            --spring.datasource.core.jdbc-url=jdbc:mysql://XXXXXX:3306/powerjob?useUnicode=true&characterEncoding=UTF-8 \
            --spring.datasource.core.username=root \
            --spring.datasource.core.password=XXXXXXX \
            --spring.data.mongodb.uri=mongodb://XXXX:27017/powerjob" \
            -v ~/docker/powerjob-server:/root/powerjob/server \
            -v ~/.m2:/root/.m2 \
            tjqq/powerjob-server:4.2.1

现在提示的错误是：


  2023-03-02 11:14:41.623  INFO 7 --- [           main] ConditionEvaluationReportLoggingListener :
  
    Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
    2023-03-02 11:14:41.662 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
    
    org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
            at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
            at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
            at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
            at java.lang.Iterable.forEach(Iterable.java:75)
            at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
            at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
            at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
            at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
            at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
            at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
            at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
            at tech.powerjob.server.PowerJobServerApplication.main(PowerJobServerApplication.java:38)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
            at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
            at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
            at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
    Caused by: java.lang.NullPointerException: null
            at springfox.documentation.spi.service.contexts.Orderings$8.compare(Orderings.java:112)
            at springfox.documentation.spi.service.contexts.Orderings$8.compare(Orderings.java:109)
            at com.google.common.collect.ComparatorOrdering.compare(ComparatorOrdering.java:40)
            at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
            at java.util.TimSort.sort(TimSort.java:234)
            at java.util.Arrays.sort(Arrays.java:1438)
            at com.google.common.collect.Ordering.sortedCopy(Ordering.java:854)
            at springfox.documentation.spring.web.plugins.WebMvcRequestHandlerProvider.requestHandlers(WebMvcRequestHandlerProvider.java:57)
            at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper$2.apply(DocumentationPluginsBootstrapper.java:138)
            at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper$2.apply(DocumentationPluginsBootstrapper.java:135)
            at com.google.common.collect.Iterators$6.transform(Iterators.java:829)
            at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
            at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
            at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1400)
            at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275)
            at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:239)
            at com.google.common.collect.FluentIterable.toList(FluentIterable.java:631)
            at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.defaultContextBuilder(DocumentationPluginsBootstrapper.java:111)
            at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.buildContext(DocumentationPluginsBootstrapper.java:96)
            at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:167)
            at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
            ... 22 common frames omitted
    
    2023-03-02 11:14:41.664 ERROR 7 --- [           main] t.p.server.PowerJobServerApplication     :

请问有没有可能是 Spring Boot 和Swagger兼容性出问题了？

**Comment by PyraAryp** [comment]
> 应该是不小心动到了其他参数导致的吧？ 你可以自己看源码，这一行配置不会影响到数据库连接层。可以说毫不相关。

可以帮忙排查下吗。

**Comment by KFCFans** [comment]
你这个错误贴出来就很清晰了。确实是高版本的 SpringBoot 和 swagger 不兼容，存在冲突。
感谢反馈，下一个版本会修复。

https://stackoverflow.com/questions/72465369/upgraded-spring-boot-to-2-7-0-failed-to-start-bean-documentationpluginsbootstr

**Comment by KFCFans** [comment]
感谢你的反馈。4.3.1版本已修复
