### ISSUE TITLE
server端因找不到Scala标准库中的Map类异常自动终止

### ISSUE THREAD

**Issue by fivedrummers** [PowerJob/PowerJob#607]
server端版本：4.3.1-bugfix，运行一段时间后，报此异常然后服务终止：
```
2023-04-04 15:11:32.848  INFO 23493 --- [ka.w-r-c-d-1414] MONITOR_LOGGER_WORKER_HEART_BEAT         : databaseSyncServer|2|4.3.1|AKKA|-|192.168.3.220:27777|3|14
Uncaught error from thread [oms-server-akka.actor.internal-dispatcher-3]: scala/collection/immutable/Map$Map3$$anon$4, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[oms-server]
java.lang.NoClassDefFoundError: scala/collection/immutable/Map$Map3$$anon$4
	at scala.collection.immutable.Map$Map3.iterator(Map.scala:411)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:636)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:634)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:920)
	at akka.remote.artery.AssociationRegistry.removeUnusedQuarantinedByAddress(Association.scala:1175)
	at akka.remote.artery.AssociationRegistry.removeUnusedQuarantined(Association.scala:1167)
	at akka.remote.artery.ArteryTransport.$anonfun$startRemoveQuarantinedAssociationTask$1(ArteryTransport.scala:442)
	at akka.actor.Scheduler$$anon$1$$anon$2.run(Scheduler.scala:83)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:53)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: scala.collection.immutable.Map$Map3$$anon$4
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: akka/actor/CoordinatedShutdown$
	at akka.remote.artery.ArteryTransport$$anon$1.run(ArteryTransport.scala:466)
Caused by: java.lang.ClassNotFoundException: akka.actor.CoordinatedShutdown$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
Exception in thread "Thread-7" java.lang.NoClassDefFoundError: io/vertx/core/file/impl/FileSystemImpl$11
	at io.vertx.core.file.impl.FileSystemImpl.delete(FileSystemImpl.java:898)
	at io.vertx.core.file.impl.FileCache.deleteCacheDir(FileCache.java:140)
	at io.vertx.core.file.impl.FileCache.lambda$runHook$0(FileCache.java:92)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.vertx.core.file.impl.FileSystemImpl$11
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
2023-04-04 15:11:36.680  INFO 23493 --- [       Thread-3] t.p.s.e.d.DatabaseLockService            : [DatabaseLockService] execute shutdown hook, release all lock(owner=192.168.3.220,num=0)
```
不知道什么原因，麻烦大神看下！

**Comment by KFCFans** [comment]
server 什么依赖都没改的情况下，大概率是自己本地包没拉下来。可以重现拉下包。
改了依赖的话，就是类冲突了，可以自己排下包。
