### ISSUE TITLE
本地worker创建任务时，写入失败，实际情况并非磁盘不足，也不是最大返回结果的长度问题(4096)

### ISSUE THREAD

**Issue by dylan-tao** [PowerJob/PowerJob#611]
## Question

4.2.0版本，本地worker创建任务时，写入失败，实际情况并非磁盘不足，也不是最大返回结果的长度问题(4096)，麻烦协助确认下

TaskTracker from request(ServerScheduleJobReq(allWorkerAddress=[192.168.1.71:27777], maxWorkerCount=0, jobId=1747, wfInstanceId=null, instanceId=524614736554229888, executeType=STANDALONE, processorType=BUILT_IN, processorInfo=com.wiseco.model.server.job.batchForecast.BatchForecastDelayProcessor, instanceTimeoutMS=0, jobParams=null, instanceParams=null, threadConcurrency=5, taskRetryNum=0, timeExpressionType=CRON, timeExpression=0 0/1 * * * ?, maxInstanceNum=0, alarmConfig=null, logConfig=null)) failed.
tech.powerjob.common.exception.PowerJobException: create root task failed for instance: 524614736554229888
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker.persistenceRootTask(CommonTaskTracker.java:138)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker.initTaskTracker(CommonTaskTracker.java:73)
	at tech.powerjob.worker.core.tracker.task.TaskTracker.<init>(TaskTracker.java:139)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker.<init>(CommonTaskTracker.java:61)
	at tech.powerjob.worker.core.tracker.task.TaskTracker.create(TaskTracker.java:158)
	at tech.powerjob.worker.actors.TaskTrackerActor.lambda$onReceiveServerScheduleJobReq$2(TaskTrackerActor.java:136)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at tech.powerjob.worker.core.tracker.task.TaskTrackerPool.atomicCreateTaskTracker(TaskTrackerPool.java:32)
	at tech.powerjob.worker.actors.TaskTrackerActor.onReceiveServerScheduleJobReq(TaskTrackerActor.java:136)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:242)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2023-04-07 15:51:54.802 [TRACE_ID:] ERROR 5602 --- [oms-akka.task-tracker-dispatcher-789] t.p.w.p.TaskPersistenceService           [TaskPersistenceService.java:56] [TaskPersistenceService] save task{taskId='0', instanceId=524614736591978624, subInstanceId=524614736591978624, taskName='OMS_ROOT_TASK', address='192.168.1.71:27777', status=1, result='null', failedCnt=0, createdTime=1680853914601, lastModifiedTime=1680853914601, lastReportTime=-1} failed.
org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database has been closed [90098-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.engine.Session.getTransaction(Session.java:1792)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1804)
	at org.h2.engine.Session.setSavepoint(Session.java:915)
	at org.h2.command.Command.executeUpdate(Command.java:244)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at tech.powerjob.worker.persistence.TaskDAOImpl.save(TaskDAOImpl.java:44)
	at tech.powerjob.worker.persistence.TaskPersistenceService.lambda$save$0(TaskPersistenceService.java:54)
	at tech.powerjob.common.utils.CommonUtils.executeWithRetry(CommonUtils.java:45)
	at tech.powerjob.worker.persistence.TaskPersistenceService.execute(TaskPersistenceService.java:349)
	at tech.powerjob.worker.persistence.TaskPersistenceService.save(TaskPersistenceService.java:54)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker.persistenceRootTask(CommonTaskTracker.java:134)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker.initTaskTracker(CommonTaskTracker.java:73)
	at tech.powerjob.worker.core.tracker.task.TaskTracker.<init>(TaskTracker.java:139)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker.<init>(CommonTaskTracker.java:61)
	at tech.powerjob.worker.core.tracker.task.TaskTracker.create(TaskTracker.java:158)
	at tech.powerjob.worker.actors.TaskTrackerActor.lambda$onReceiveServerScheduleJobReq$2(TaskTrackerActor.java:136)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at tech.powerjob.worker.core.tracker.task.TaskTrackerPool.atomicCreateTaskTracker(TaskTrackerPool.java:32)
	at tech.powerjob.worker.actors.TaskTrackerActor.onReceiveServerScheduleJobReq(TaskTrackerActor.java:136)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:242)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalStateException: Writing to nio:/root/powerjob/worker/h2/d9f8ecfacb3a4c109a56637ad9c0407e/powerjob_worker_db.mv.db failed; length 4096 at 45056 [1.4.200/2]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.DataUtils.writeFully(DataUtils.java:479)
	at org.h2.mvstore.FileStore.writeFully(FileStore.java:113)
	at org.h2.mvstore.MVStore.write(MVStore.java:1111)
	at org.h2.mvstore.MVStore.moveChunk(MVStore.java:1935)
	at org.h2.mvstore.MVStore.compactMoveChunks(MVStore.java:1839)
	at org.h2.mvstore.MVStore.compactMoveChunks(MVStore.java:1772)
	at org.h2.mvstore.MVStore.doMaintenance(MVStore.java:2848)
	at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2788)
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3290)
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:66)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:89)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:778)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:764)
	at org.h2.store.fs.FileNio.write(FilePathNio.java:79)
	at org.h2.mvstore.DataUtils.writeFully(DataUtils.java:475)

**Comment by KFCFans** [comment]
从错误看是数据库连接被关闭了，当时 Java 进程还在吗？如果已经不在了，大概率是分配的资源不够导致被进程被 kill 了。
