### ISSUE TITLE
ServerElectionService 感觉有点问题

### ISSUE THREAD

**Issue by benyVip** [PowerJob/PowerJob#616]
主干版本：
对应的类：ServerElectionService

心跳在检测，如果是已选完主了，请求本地的ping服务报错：
  at tech.powerjob.remote.http.vertx.VertxTransporter.lambda$post$2(VertxTransporter.java:76)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)

对应的代码：我发现是本机请求本机，这里是不是不应该这么做？
 public String elect(ServerDiscoveryRequest request) {
        if (!accurate()) {
            final String currentServer = request.getCurrentServer();
            // 如果是本机，就不需要查数据库那么复杂的操作了，直接返回成功
            Optional<ProtocolInfo> localProtocolInfoOpt = Optional.ofNullable(transportService.allProtocols().get(request.getProtocol()));
            if (localProtocolInfoOpt.isPresent() && localProtocolInfoOpt.get().getAddress().equals(currentServer)) {
                log.debug("[ServerElectionService] this server[{}] is worker's current server, skip check", currentServer);
                return currentServer;
            }
        }
        return getServer0(request);
   }

**Comment by benyVip** [comment]
![image](https://user-images.githubusercontent.com/24514338/232763316-8bc613da-10ab-406e-b4e2-61ebcb9be141.png)
对应的报错
