### ISSUE TITLE
springboot低于2.7.4的版本，的项目，无法注册机器到控制台

### ISSUE THREAD

**Issue by disikoudad** [PowerJob/PowerJob#622]
感谢作者大大做了这么好一个框架，我遇到了一个问题，找了issue没有解决，想问问大家有没有解决方案
我使用4.3.2的版本，其中的simple示例程序，springboot版本是2.7..4，可以成功注册到service，但是我搭建了另一个项目，springboot版本是2.6.3，项目可以启动，但是无法在service看到注册信息

我测试了多次，可以确认就是，改了springboot版本，导致无法注册

**Comment by rongyanjuren** [comment]
我原本的版本是2.2.4.RELEASE，死活注册不上，但是work可以启动，就是页面找不到
<img width="2338" alt="image" src="https://user-images.githubusercontent.com/49813094/233888221-edbdb87c-ed10-4a45-8463-6e7304cadf4b.png">
换了一个work的springboot版本，换成2.7.4后启动报空指针
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException

**Comment by xiaodi-hub** [comment]
我也是启动报错：springboot 为2.2.6.RELEASE，希望得到解决
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initPowerJob' defined in class path resource [tech/powerjob/worker/autoconfigure/PowerJobAutoConfiguration.class]: Invocation of init method failed; nested exception is tech.powerjob.common.exception.PowerJobException: no server available!
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.example.App.main(App.java:12) [classes/:na]
Caused by: tech.powerjob.common.exception.PowerJobException: no server available!
	at tech.powerjob.worker.PowerJobWorker.assertAppName(PowerJobWorker.java:168) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.PowerJobWorker.init(PowerJobWorker.java:77) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.PowerJobSpringWorker.afterPropertiesSet(PowerJobSpringWorker.java:39) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 16 common frames omitted


Process finished with exit code 1

**Comment by KFCFans** [comment]
好的，应该是为了做 SpringBoot3 兼容引入的 BUG，我们会在后续版本修复。
暂时可以选择手动初始化的方式启动 powerjob-worker，参考文档：https://www.yuque.com/powerjob/guidence/ygonln

```
@Configuration
public class PowerJobWorkerConfiguration {

    @Bean
    public PowerJobSpringWorker initPowerJobWorker() throws Exception {

        // 1. 创建配置文件
        PowerJobWorkerConfig config = new PowerJobWorkerConfig();
        config.setPort(28888);
        config.setAppName("my-java-application");
        config.setServerAddress(Lists.newArrayList("127.0.0.1:7700", "127.0.0.1:7701"));
        // 如果没有大型 Map/MapReduce 的需求，建议使用内存来加速计算
        config.setStoreStrategy(StoreStrategy.DISK);

        // 2. 创建 Worker 对象，设置配置文件（注意 Spring 用户需要使用 PowerJobSpringWorker，而不是 PowerJobWorker）
        PowerJobSpringWorker worker = new PowerJobSpringWorker(config);
        return worker;
    }
}```

**Comment by rongyanjuren** [comment]
> 好的，应该是为了做 SpringBoot3 兼容引入的 BUG，我们会在后续版本修复。 暂时可以选择手动初始化的方式启动 powerjob-worker，参考文档：https://www.yuque.com/powerjob/guidence/ygonln
> 
> ```
> @Configuration
> public class PowerJobWorkerConfiguration {
> 
>     @Bean
>     public PowerJobSpringWorker initPowerJobWorker() throws Exception {
> 
>         // 1. 创建配置文件
>         PowerJobWorkerConfig config = new PowerJobWorkerConfig();
>         config.setPort(28888);
>         config.setAppName("my-java-application");
>         config.setServerAddress(Lists.newArrayList("127.0.0.1:7700", "127.0.0.1:7701"));
>         // 如果没有大型 Map/MapReduce 的需求，建议使用内存来加速计算
>         config.setStoreStrategy(StoreStrategy.DISK);
> 
>         // 2. 创建 Worker 对象，设置配置文件（注意 Spring 用户需要使用 PowerJobSpringWorker，而不是 PowerJobWorker）
>         PowerJobSpringWorker worker = new PowerJobSpringWorker(config);
>         return worker;
>     }
> }```
> ```

感谢大佬，这个方法没问题

**Comment by dudiao** [comment]
@disikoudad 可以参考这个：https://github.com/PowerJob/PowerJob/issues/667#issuecomment-1996625269
