### ISSUE TITLE
SpringDatasourceSqlProcessor  官方处理器执行失败

### ISSUE THREAD

**Issue by zxxjyn** [PowerJob/PowerJob#632]
按照说明对 SpringDatasourceSqlProcessor  进行配置，使用 tech.powerjob.official.processors.impl.sql.SpringDatasourceSqlProcessor，调度执行失败。

具体配置信息：
![image](https://user-images.githubusercontent.com/42338930/236779554-a51911fb-fde8-429a-be4e-024899126413.png)

执行结果：
![image](https://user-images.githubusercontent.com/42338930/236779662-bdb28767-f2df-47ea-8439-9da365e20dec.png)

报错日志：
```
2023-05-08 16:44:56.313  INFO 31752 --- [b-worker-core-2] t.p.w.background.WorkerHealthReporter    : [WorkerHealthReporter] report health status,appId:1,appName:SKYY,isOverload:false,maxLightweightTaskNum:1024,currentLightweightTaskNum:0,maxHeavyweightTaskNum:64,currentHeavyweightTaskNum:0
2023-05-08 16:44:59.083  INFO 31752 --- [worker-thread-3] t.p.w.processor.PowerJobProcessorLoader  : [ProcessorFactory] start to load Processor: ProcessorDefinition(processorType=BUILT_IN, processorInfo=tech.powerjob.official.processors.impl.sql.SpringDatasourceSqlProcessor)
2023-05-08 16:44:59.084  INFO 31752 --- [worker-thread-3] t.p.w.processor.PowerJobProcessorLoader  : [ProcessorFactory] [BuiltInSpringProcessorFactory] try to load processor: ProcessorDefinition(processorType=BUILT_IN, processorInfo=tech.powerjob.official.processors.impl.sql.SpringDatasourceSqlProcessor)
2023-05-08 16:44:59.085  WARN 31752 --- [worker-thread-3] t.p.w.p.i.BuiltInSpringProcessorFactory  : [ProcessorFactory] can't find the processor in SPRING
2023-05-08 16:44:59.085  INFO 31752 --- [worker-thread-3] t.p.w.processor.PowerJobProcessorLoader  : [ProcessorFactory] [BuiltInDefaultProcessorFactory] try to load processor: ProcessorDefinition(processorType=BUILT_IN, processorInfo=tech.powerjob.official.processors.impl.sql.SpringDatasourceSqlProcessor)
2023-05-08 16:44:59.086  WARN 31752 --- [worker-thread-3] t.p.w.p.i.BuiltInDefaultProcessorFactory : [ProcessorFactory] load local Processor(className = tech.powerjob.official.processors.impl.sql.SpringDatasourceSqlProcessor) failed.

java.lang.NoSuchMethodException: tech.powerjob.official.processors.impl.sql.SpringDatasourceSqlProcessor.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_191]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[na:1.8.0_191]
	at tech.powerjob.worker.processor.impl.BuiltInDefaultProcessorFactory.build(BuiltInDefaultProcessorFactory.java:34) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.processor.PowerJobProcessorLoader.lambda$load$0(PowerJobProcessorLoader.java:44) [powerjob-worker-4.3.2.jar:4.3.2]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_191]
	at tech.powerjob.worker.processor.PowerJobProcessorLoader.load(PowerJobProcessorLoader.java:33) [powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.core.tracker.task.light.LightTaskTracker.<init>(LightTaskTracker.java:90) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.core.tracker.task.light.LightTaskTracker.create(LightTaskTracker.java:126) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.actors.TaskTrackerActor.lambda$onReceiveServerScheduleJobReq$1(TaskTrackerActor.java:142) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_191]
	at tech.powerjob.worker.core.tracker.manager.LightTaskTrackerManager.atomicCreateTaskTracker(LightTaskTrackerManager.java:32) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.actors.TaskTrackerActor.onReceiveServerScheduleJobReq(TaskTrackerActor.java:142) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.actors.WorkerActor.onReceiveServerScheduleJobReq(WorkerActor.java:44) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at tech.powerjob.remote.http.HttpVertxCSInitializer.lambda$buildRequestHandler$3(HttpVertxCSInitializer.java:119) ~[powerjob-remote-impl-http-4.3.2.jar:4.3.2]
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135) ~[vertx-core-4.3.7.jar:4.3.7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]

2023-05-08 16:44:59.086  INFO 31752 --- [worker-thread-3] t.p.w.processor.PowerJobProcessorLoader  : [ProcessorFactory] [JarContainerProcessorFactory] can't load type=BUILT_IN, skip!
2023-05-08 16:44:59.086 ERROR 31752 --- [worker-thread-3] t.p.w.c.t.task.light.LightTaskTracker    : [TaskTracker-535860639252349120] fail to create TaskTracker for req:ServerScheduleJobReq(allWorkerAddress=[192.168.97.124:27778], maxWorkerCount=0, jobId=1, wfInstanceId=null, instanceId=535860639252349120, executeType=STANDALONE, processorType=BUILT_IN, processorInfo=tech.powerjob.official.processors.impl.sql.SpringDatasourceSqlProcessor, instanceTimeoutMS=0, jobParams={
    "dataSourceName": "jobDataSource",
    "sql": "select 'x' from t_example",
    "timeout": 10,
    "showResult": true
}, instanceParams=null, threadConcurrency=5, taskRetryNum=1, timeExpressionType=DAILY_TIME_INTERVAL, timeExpression={"interval":"10","startTimeOfDay":"17:49:33","intervalUnit":"SECONDS","daysOfWeek":[1,2,3,4,5,6,7],"endTimeOfDay":"23:40:41"}, maxInstanceNum=0, alarmConfig={"alertThreshold":0,"silenceWindowLen":0,"statisticWindowLen":0}, logConfig={"level":2,"type":1}) 
2023-05-08 16:44:59.087  WARN 31752 --- [worker-thread-3] t.p.w.c.t.task.light.LightTaskTracker    : [TaskTracker-535860639252349120] remove TaskTracker,task status WORKER_RECEIVED,start time:null,end time:null,real cost:unknown,total time:3
2023-05-08 16:44:59.087  WARN 31752 --- [worker-thread-3] t.p.w.core.tracker.task.TaskTracker      : [TaskTracker-535860639252349120] create TaskTracker from request(ServerScheduleJobReq(allWorkerAddress=[192.168.97.124:27778], maxWorkerCount=0, jobId=1, wfInstanceId=null, instanceId=535860639252349120, executeType=STANDALONE, processorType=BUILT_IN, processorInfo=tech.powerjob.official.processors.impl.sql.SpringDatasourceSqlProcessor, instanceTimeoutMS=0, jobParams={
    "dataSourceName": "jobDataSource",
    "sql": "select 'x' from t_example",
    "timeout": 10,
    "showResult": true
}, instanceParams=null, threadConcurrency=5, taskRetryNum=1, timeExpressionType=DAILY_TIME_INTERVAL, timeExpression={"interval":"10","startTimeOfDay":"17:49:33","intervalUnit":"SECONDS","daysOfWeek":[1,2,3,4,5,6,7],"endTimeOfDay":"23:40:41"}, maxInstanceNum=0, alarmConfig={"alertThreshold":0,"silenceWindowLen":0,"statisticWindowLen":0}, logConfig={"level":2,"type":1})) failed.

tech.powerjob.common.exception.PowerJobException: fetch Processor failed, please check your processorType and processorInfo config
	at tech.powerjob.worker.processor.PowerJobProcessorLoader.lambda$load$0(PowerJobProcessorLoader.java:53) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_191]
	at tech.powerjob.worker.processor.PowerJobProcessorLoader.load(PowerJobProcessorLoader.java:33) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.core.tracker.task.light.LightTaskTracker.<init>(LightTaskTracker.java:90) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.core.tracker.task.light.LightTaskTracker.create(LightTaskTracker.java:126) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.actors.TaskTrackerActor.lambda$onReceiveServerScheduleJobReq$1(TaskTrackerActor.java:142) [powerjob-worker-4.3.2.jar:4.3.2]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_191]
	at tech.powerjob.worker.core.tracker.manager.LightTaskTrackerManager.atomicCreateTaskTracker(LightTaskTrackerManager.java:32) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.actors.TaskTrackerActor.onReceiveServerScheduleJobReq(TaskTrackerActor.java:142) [powerjob-worker-4.3.2.jar:4.3.2]
	at tech.powerjob.worker.actors.WorkerActor.onReceiveServerScheduleJobReq(WorkerActor.java:44) ~[powerjob-worker-4.3.2.jar:4.3.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at tech.powerjob.remote.http.HttpVertxCSInitializer.lambda$buildRequestHandler$3(HttpVertxCSInitializer.java:119) ~[powerjob-remote-impl-http-4.3.2.jar:4.3.2]
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135) ~[vertx-core-4.3.7.jar:4.3.7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]

```

代码：
```
package com.job.worker.config;


import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.h2.Driver;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.DependsOn;
import org.springframework.stereotype.Component;
import tech.powerjob.common.utils.CommonUtils;
import tech.powerjob.official.processors.impl.sql.SpringDatasourceSqlProcessor;
import tech.powerjob.worker.PowerJobWorker;

import javax.annotation.Resource;
import javax.sql.DataSource;

/**
 * @author Echo009
 * @since 2021/3/10
 */
@Configuration
@ConditionalOnBean(PowerJobWorker.class)
public class SqlProcessorConfiguration {
    @Autowired
    DataSource jobDataSource;

    @Bean
    @DependsOn({"initPowerJob"})
    public DataSource sqlProcessorDataSource() {
        String path = System.getProperty("user.home") + "/test/h2/" + CommonUtils.genUUID() + "/";
        String jdbcUrl = String.format("jdbc:h2:file:%spowerjob_sql_processor_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false", path);
        HikariConfig config = new HikariConfig();
        config.setDriverClassName(Driver.class.getName());
        config.setJdbcUrl(jdbcUrl);
        config.setAutoCommit(true);
        // 池中最小空闲连接数量
        config.setMinimumIdle(1);
        // 池中最大连接数量
        config.setMaximumPoolSize(10);
        return new HikariDataSource(config);
    }

    @Bean
    public DataSource jobProcessorDataSource() {
        return jobDataSource;
    }

    @Bean
    @Resource
    public SpringDatasourceSqlProcessor simpleSpringSqlProcessor(@Qualifier("sqlProcessorDataSource") DataSource dataSource) {
        SpringDatasourceSqlProcessor springDatasourceSqlProcessor = new SpringDatasourceSqlProcessor(dataSource);
        // do nothing
        springDatasourceSqlProcessor.registerSqlValidator("fakeSqlValidator", sql -> true);
        // 排除掉包含 drop 的 SQL
        springDatasourceSqlProcessor.registerSqlValidator("interceptDropValidator", sql -> sql.matches("^(?i)((?!drop).)*$"));
        // do nothing
        springDatasourceSqlProcessor.setSqlParser((sql, taskContext) -> sql);
        springDatasourceSqlProcessor.registerDataSource("jobDataSource", jobDataSource);
        return springDatasourceSqlProcessor;
    }
}

```

**Expected behavior**

**Environment**
 - PowerJob Version: 4.3.2
 - Java Version: Oracle jdk 8.1.9.1
 - OS: windows 11

---
麻烦帮忙看一下 SpringDatasourceSqlProcessor  的问题，谢谢。

**Comment by DeanWanghewei** [comment]
应该是 powerjob-official-processors 包与 powerjob-worker 包版本不一致导致的。替换一下相同的包重新启动执行看看。

**Comment by zxxjyn** [comment]
看了一下版本包都一致，是4.3.2，目前解决方案是自定义了一个 http-processors，完成相同的操作。
SpringDatasourceSqlProcessor bean注入未找到的问题，我有时间排查一下，有结果在这跟新，谢谢。
