### ISSUE TITLE
ERROR a.a.OneForOneStrategy - null

### ISSUE THREAD

**Issue by jcjgithub** [PowerJob/PowerJob#658]
**Describe the bug**
023-06-16 14:55:13.047 [oms-server-akka.actor.default-dispatcher-5] d
java.lang.NullPointerException: null
	at tech.powerjob.server.core.handler.AbWorkerRequestHandler.processWorkerHeartbeat(AbWorkerRequestHandler.java:67)
	at tech.powerjob.server.core.handler.impl.WorkerRequestAkkaHandler.lambda$createReceive$0(WorkerRequestAkkaHandler.java:45)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Environment**
 - PowerJob Version: 4.2.0
 - Java Version: openjdk version "1.8.0_252"
 - OS: centos7.9
 -docker 容器运行 

业务模块也是容器运行。

**Screenshots**

**Additional context**

**Comment by jcjgithub** [comment]
![image](https://github.com/PowerJob/PowerJob/assets/66168320/a86b04f4-ed97-4870-b11f-5d3c582953dc)
远程debug 发现是传了这个这样的数据过来
