### ISSUE TITLE
容器部署下载jar包时候，每次点部署，agent报错 downloadJar 502，前端显示部署成功，但是机器列表没有worker，server端无明显错误，下载jar链接在浏览器中正常下载

### ISSUE THREAD

**Issue by Jehol1983** [PowerJob/PowerJob#707]
2023-08-09 23:22:34 |INFO  |oms-akka.common-dispatcher-162 |t.p.w.c.OmsContainerFactory |[OmsContainer-772] start to deploy container(name=demo,version=6f07b56623d4d187ef28b0675e0d84d7,downloadUrl=http://ip:7700/container/downloadJar?version=6f07b56623d4d187ef28b0675e0d84d7)
2023-08-09 23:22:37 |INFO  |powerjob-worker-core-1 |t.p.w.b.WorkerHealthReporter |[WorkerHealthReporter] report health status,appId:19,appName:plm,isOverload:false,maxLightweightTaskNum:1024,currentLightweightTaskNum:0,maxHeavyweightTaskNum:64,currentHeavyweightTaskNum:0
2023-08-09 23:22:37 |ERROR |oms-akka.common-dispatcher-162 |t.p.w.c.OmsContainerFactory |[OmsContainer-772] deployContainer(name=demo,version=6f07b56623d4d187ef28b0675e0d84d7) failed.
java.io.IOException: Server returned HTTP response code: 502 for URL: http://ip:7700/container/downloadJar?version=6f07b56623d4d187ef28b0675e0d84d7
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1097)
	at tech.powerjob.worker.container.OmsContainerFactory.deployContainer(OmsContainerFactory.java:96)
	at tech.powerjob.worker.actors.WorkerActor.onReceiveServerDeployContainerRequest(WorkerActor.java:34)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at tech.powerjob.remote.akka.AkkaProxyActor.onReceiveProcessorReportTaskStatusReq(AkkaProxyActor.java:56)
	at tech.powerjob.remote.akka.AkkaProxyActor.lambda$null$0(AkkaProxyActor.java:43)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:242)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:242)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:242)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)

**Comment by KFCFans** [comment]
收到，后续进行问题确认和排查

**Comment by yogaxu** [comment]
downloadUrl=http://ip:7700/...

会不会是你配置的问题，回去不到网卡信息
