### ISSUE TITLE
使用oracle启动server,日志总是打印这个错误，但是我的定时任务是正常的

### ISSUE THREAD

**Issue by litong0531** [PowerJob/PowerJob#746]
2023-09-20 15:47:28.205  WARN 25644 --- [        PJ-BG-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 42104, SQLState: 42S04
2023-09-20 15:47:28.205 ERROR 25644 --- [        PJ-BG-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table "LOCAL_INSTANCE_LOG" not found (this database is empty); SQL statement:
select localinsta0_.id as id1_0_, localinsta0_.instance_id as instance_id2_0_, localinsta0_.log_content as log_content3_0_, localinsta0_.log_level as log_level4_0_, localinsta0_.log_time as log_time5_0_, localinsta0_.worker_address as worker_address6_0_ from local_instance_log localinsta0_ where localinsta0_.instance_id=? [42104-214]
2023-09-20 15:47:28.274  INFO 25644 --- [TimeIntervalJob] t.p.s.c.scheduler.PowerScheduleService   : [NormalScheduler] TimeExpressionType.DAILY_TIME_INTERVAL(v=11) job schedule use 1324 ms.
Hibernate: select localinsta0_.id as id1_0_, localinsta0_.instance_id as instance_id2_0_, localinsta0_.log_content as log_content3_0_, localinsta0_.log_level as log_level4_0_, localinsta0_.log_time as log_time5_0_, localinsta0_.worker_address as worker_address6_0_ from local_instance_log localinsta0_ where localinsta0_.instance_id=?
2023-09-20 15:47:28.309  WARN 25644 --- [        PJ-BG-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 42104, SQLState: 42S04
2023-09-20 15:47:28.309 ERROR 25644 --- [        PJ-BG-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table "LOCAL_INSTANCE_LOG" not found (this database is empty); SQL statement:
select localinsta0_.id as id1_0_, localinsta0_.instance_id as instance_id2_0_, localinsta0_.log_content as log_content3_0_, localinsta0_.log_level as log_level4_0_, localinsta0_.log_time as log_time5_0_, localinsta0_.worker_address as worker_address6_0_ from local_instance_log localinsta0_ where localinsta0_.instance_id=? [42104-214]
Hibernate: select localinsta0_.id as id1_0_, localinsta0_.instance_id as instance_id2_0_, localinsta0_.log_content as log_content3_0_, localinsta0_.log_level as log_level4_0_, localinsta0_.log_time as log_time5_0_, localinsta0_.worker_address as worker_address6_0_ from local_instance_log localinsta0_ where localinsta0_.instance_id=?
2023-09-20 15:47:28.412  WARN 25644 --- [        PJ-BG-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 42104, SQLState: 42S04
2023-09-20 15:47:28.412 ERROR 25644 --- [        PJ-BG-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table "LOCAL_INSTANCE_LOG" not found (this database is empty); SQL statement:
select localinsta0_.id as id1_0_, localinsta0_.instance_id as instance_id2_0_, localinsta0_.log_content as log_content3_0_, localinsta0_.log_level as log_level4_0_, localinsta0_.log_time as log_time5_0_, localinsta0_.worker_address as worker_address6_0_ from local_instance_log localinsta0_ where localinsta0_.instance_id=? [42104-214]
2023-09-20 15:47:28.414  WARN 25644 --- [        PJ-BG-3] t.p.s.core.instance.InstanceLogService   : [InstanceLog-584769790841716928] delete local instanceLog failed.

org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select localinsta0_.id as id1_0_, localinsta0_.instance_id as instance_id2_0_, localinsta0_.log_content as log_content3_0_, localinsta0_.log_level as log_level4_0_, localinsta0_.log_time as log_time5_0_, localinsta0_.worker_address as worker_address6_0_ from local_instance_log localinsta0_ where localinsta0_.instance_id=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:259)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy2/jdk.proxy2.$Proxy165.deleteByInstanceId(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at tech.powerjob.server.persistence.monitor.DatabaseMonitorAspect.wrapperMonitor(DatabaseMonitorAspect.java:54)
	at tech.powerjob.server.persistence.monitor.DatabaseMonitorAspect.monitorLocalDB(DatabaseMonitorAspect.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy2/jdk.proxy2.$Proxy165.deleteByInstanceId(Unknown Source)
	at tech.powerjob.server.core.instance.InstanceLogService.lambda$sync$3(InstanceLogService.java:235)
	at tech.powerjob.common.utils.CommonUtils.executeWithRetry(CommonUtils.java:45)
	at tech.powerjob.common.utils.CommonUtils.executeWithRetry0(CommonUtils.java:49)
	at tech.powerjob.server.core.instance.InstanceLogService.sync(InstanceLogService.java:235)
	at tech.powerjob.server.core.instance.InstanceLogService$$FastClassBySpringCGLIB$$333783dd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
	at org.hibernate.loader.Loader.doQuery(Loader.java:956)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
	at org.hibernate.loader.Loader.doList(Loader.java:2868)
	at org.hibernate.loader.Loader.doList(Loader.java:2850)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
	at org.hibernate.loader.Loader.list(Loader.java:2677)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
	at org.hibernate.query.Query.getResultList(Query.java:165)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:76)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$DeleteExecution.doExecute(JpaQueryExecution.java:274)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:156)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:144)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:160)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:81)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	... 49 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "LOCAL_INSTANCE_LOG" not found (this database is empty); SQL statement:
select localinsta0_.id as id1_0_, localinsta0_.instance_id as instance_id2_0_, localinsta0_.log_content as log_content3_0_, localinsta0_.log_level as log_level4_0_, localinsta0_.log_time as log_time5_0_, localinsta0_.worker_address as worker_address6_0_ from local_instance_log localinsta0_ where localinsta0_.instance_id=? [42104-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8385)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8369)
	at org.h2.command.Parser.readTableOrView(Parser.java:8358)
	at org.h2.command.Parser.readTablePrimary(Parser.java:1863)
	at org.h2.command.Parser.readTableReference(Parser.java:2334)
	at org.h2.command.Parser.parseSelectFromPart(Parser.java:2772)
	at org.h2.command.Parser.parseSelect(Parser.java:2878)
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762)
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2633)
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612)
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605)
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2598)
	at org.h2.command.Parser.parseQuery(Parser.java:2567)
	at org.h2.command.Parser.parsePrepared(Parser.java:724)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	... 83 common frames omitted

**Comment by dudiao** [comment]
`local_instance_log`这个表，是本地h2数据库中的，用于存放临时的日志，为什么会出现到 oracle 里呢

**Comment by litong0531** [comment]
我也不知道呀，我直接拉的最新的镜像部署的，oracle数据库我连接的时候只是建了一个POWERJOB-PRODUCT的角色

**Comment by limng06** [comment]
> spring.datasource.local.hibernate.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect 加个配置

多半是建表的时候因为生成的ddl错误导致，指定下local的数据库方言有用的
