### ISSUE TITLE
powerjob 调度中心报错，如图

### ISSUE THREAD

**Issue by lffyd** [PowerJob/PowerJob#759]
![Uploading 企业微信截图_16969956057089.png…]()

**Comment by lffyd** [comment]
SYSTEM: connected successfully, start to deploy container: 5
SYSTEM: start to git clone the code repo, using config: {"repo":"https://gitee.com/KFCFans/PowerJob-Container-Template.git","branch":"master","username":"","password":""}
SYSTEM: new version detected, from init to f9375574b9b5759d16b0657e7150399e7406aad7.
SYSTEM: git clone successfully, star to compile the project.
SYSTEM: deploy failed because of the exception
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: /root/powerjob-server/temporary/fa4aa42f743748248639c36c5658d66d/target at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:541) at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:517) at com.github.kfcfans.powerjob.server.service.ContainerService.prepareJarFile(ContainerService.java:387) at com.github.kfcfans.powerjob.server.service.ContainerService.deploy(ContainerService.java:235) at com.github.kfcfans.powerjob.server.web.websocket.ContainerDeployServerEndpoint.onOpen(ContainerDeployServerEndpoint.java:36) at sun.reflect.GeneratedMethodAccessor668.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at io.undertow.websockets.jsr.annotated.BoundMethod.invoke(BoundMethod.java:87) at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$3.run(AnnotatedEndpoint.java:158) at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170) at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:610) at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:600) at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint.invokeMethod(AnnotatedEndpoint.java:153) at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint.onOpen(AnnotatedEndpoint.java:102) at io.undertow.websockets.jsr.EndpointSessionHandler.onConnect(EndpointSessionHandler.java:129) at io.undertow.websockets.jsr.JsrWebSocketFilter$1.handleUpgrade(JsrWebSocketFilter.java:165) at io.undertow.server.protocol.http.HttpReadListener.exchangeComplete(HttpReadListener.java:389) at io.undertow.server.protocol.http.HttpServerConnection.exchangeComplete(HttpServerConnection.java:244) at io.undertow.server.HttpServerExchange.invokeExchangeCompleteListeners(HttpServerExchange.java:1285) at io.undertow.server.HttpServerExchange.terminateResponse(HttpServerExchange.java:1569) at io.undertow.server.Connectors.terminateResponse(Connectors.java:159) at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:199) at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:197) at io.undertow.conduits.HeadStreamSinkConduit.exitFlush(HeadStreamSinkConduit.java:192) at io.undertow.conduits.HeadStreamSinkConduit.flush(HeadStreamSinkConduit.java:133) at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162) at io.undertow.channels.DetachableStreamSinkChannel.flush(DetachableStreamSinkChannel.java:119) at org.xnio.channels.Channels.flushBlocking(Channels.java:63) at io.undertow.servlet.spec.ServletOutputStreamImpl.close(ServletOutputStreamImpl.java:619) at io.undertow.servlet.spec.HttpServletResponseImpl.closeStreamAndWriter(HttpServletResponseImpl.java:534) at io.undertow.servlet.spec.HttpServletResponseImpl.responseDone(HttpServletResponseImpl.java:623) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:328) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:370) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:836) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at java.lang.Thread.run(Thread.java:748)
