### ISSUE TITLE
Invocation of init method failed; nested exception is tech.powerjob.common.exception.PowerJobException: can't load CSInitializer[HTTP], ensure your package name start with 'tech.powerjob' and import the dependencies!

### ISSUE THREAD

**Issue by MartinKayJr** [PowerJob/PowerJob#788]
rror starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-11-25 17:00:52.621 [ERROR] org.springframework.boot.SpringApplication:[837] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initPowerJobWorker' defined in class path resource [org/normalization/basic/config/PowerJobWorkerConfiguration.class]: Invocation of init method failed; nested exception is tech.powerjob.common.exception.PowerJobException: can't load CSInitializer[HTTP], ensure your package name start with 'tech.powerjob' and import the dependencies!
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.normalization.NormalizationStandalone.main(NormalizationStandalone.java:20)
Caused by: tech.powerjob.common.exception.PowerJobException: can't load CSInitializer[HTTP], ensure your package name start with 'tech.powerjob' and import the dependencies!
	at tech.powerjob.remote.framework.engine.impl.CSInitializerFactory.build(CSInitializerFactory.java:42)
	at tech.powerjob.remote.framework.engine.impl.PowerJobRemoteEngine.start(PowerJobRemoteEngine.java:35)
	at tech.powerjob.worker.PowerJobWorker.init(PowerJobWorker.java:109)
	at tech.powerjob.worker.PowerJobSpringWorker.afterPropertiesSet(PowerJobSpringWorker.java:40)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	... 17 common frames omitted

**Comment by lvhjean** [comment]
这个问题有解决方案吗？

**Comment by lvhjean** [comment]
@MartinKayJr 
这个排查好长时间，发现是打包问题不支持；可能war包和jar包机制还是不一样的（这个再研究不在这里说）；
将包类型war改为jar即可；
- 看有说reflections版本低的我看已经是最新版了；
- 还有说没有加过滤Scanner，这回不懂就查了下reflections的github库的例子，大佬写的也没问题虽然是0.9.X的方式，但是还是被支持的；
- 最后采用尝试的太多，试了一下将war改为jar，居然Ok了。

**Comment by KFCFans** [comment]
5.0.1 版本的 worker 官方组件加载不再依赖 reflections 了，这个问题应该已经被解决了。
