### ISSUE TITLE
powerjob-worker 不支持 graalvm 

### ISSUE THREAD

**Issue by lmm1990** [PowerJob/PowerJob#868]
**Describe the bug**
powerjob-worker 不支持 graalvm 

**To Reproduce**
1. 创建springboot项目
2. 引入`implementation "tech.powerjob:powerjob-worker-spring-boot-starter:5.0.0-beta2"`
3. bootBuildImage

**Expected behavior**
期望编译成功

**Environment**
 - PowerJob Version: 5.0.0-beta2
 - Java Version: graalvm 21.0.2
 - OS: CentOS 8.1

**Screenshots**
2024-03-13 13:27:20.491  INFO 1 --- [           main] org.reflections.Reflections              : Reflections took 0 ms to scan 0 urls, producing 0 keys and 0 values
2024-03-13 13:27:20.491  INFO 1 --- [           main] t.p.r.f.e.impl.CSInitializerFactory      : [CSInitializerFactory] scan subTypeOf CSInitializer: []
2024-03-13 13:27:20.491 ERROR 1 --- [           main] tech.powerjob.worker.PowerJobWorker      : [PowerJobWorker] initialize PowerJobWorker failed, using 58.11 ms.

tech.powerjob.common.exception.PowerJobException: can't load CSInitializer[HTTP], ensure your package name start with 'tech.powerjob' and import the dependencies!
        at tech.powerjob.remote.framework.engine.impl.CSInitializerFactory.build(CSInitializerFactory.java:42)
        at tech.powerjob.remote.framework.engine.impl.PowerJobRemoteEngine.start(PowerJobRemoteEngine.java:35)
        at tech.powerjob.worker.PowerJobWorker.init(PowerJobWorker.java:112)
        at tech.powerjob.worker.PowerJobSpringWorker.afterPropertiesSet(PowerJobSpringWorker.java:40)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:950)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
        at cc.metafusion.rta.schedule.RtaScheduleApplication.main(RtaScheduleApplication.java:28)
        at java.base@21.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

**Additional context**

powerjob使用了`implementation 'org.reflections:reflections:0.10.2'`，但`reflections`不支持高版本jdk或graalvm，建议换掉这个框架，以得到更好的兼容性

**Comment by lmm1990** [comment]
https://github.com/ronmamo/reflections
❗ Please note: Reflections library is currently NOT under active development or maintenance ❗

**Comment by KFCFans** [comment]
运行时反射获取的类在 graavl 编译阶段由于无任何直接依赖不会被编译进去。和 reflections
这个库其实没关系。你在代码里手动依赖下相关协议的实现，或者在编译配置里把相关的类配置进去就好了。

lmm1990 ***@***.***>于2024年3月13日 周三14:39写道：

**Comment by KFCFans** [comment]
最简单的方式，随便找个地方写一个 `new tech.powerjob.remote.http.HttpVertxCSInitializer()` ，重新编译，问题解决

**Comment by yinian** [comment]
哥们，给new 一个，我这里new 了，还是报按个错

**Comment by KFCFans** [comment]
`Reflections took 0 ms to scan 0 urls, producing 0 keys and 0 values`
好吧，我仔细看了下错误提示，可能确实是类库的兼容性问题。想办法 fix 一下🤔

**Comment by KFCFans** [comment]
5.0.1 的 worker 已修复（就算是 4.3.8 以上的 server 应该也可以用）

**Comment by yinian** [comment]
具体是因为啥原因，亲
