### ISSUE TITLE
请教大佬 AskTimeoutException异常问题

### ISSUE THREAD

**Issue by lulu-0827** [PowerJob/PowerJob#877]
**Describe the bug**
`2024-03-16 23:15:08.158 [ctttp-649387666143445120-1] WARN  t.p.worker.core.tracker.task.CommonTaskTracker - [TaskTracker-649387666143445120] report finished status failed, result=应用运行正常！.
java.util.concurrent.ExecutionException: akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://oms/deadLetters), Path(/)]] after [5000 ms]. Message of type [tech.powerjob.common.request.TaskTrackerReportInstanceStatusReq]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:91)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:91)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.package$.blocking(package.scala:124)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:91)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.innerRun(CommonTaskTracker.java:258)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.run(CommonTaskTracker.java:324)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://oms/deadLetters), Path(/)]] after [5000 ms]. Message of type [tech.powerjob.common.request.TaskTrackerReportInstanceStatusReq]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
2024-03-16 23:15:11.519 [oms-worker-timing-pool-2] WARN  t.p.worker.background.ServerDiscoveryService - [PowerDiscovery] can't find any available server, this worker[appId=85] has been quarantined.
2024-03-16 23:15:21.159 [oms-akka.actor.default-dispatcher-3280] WARN  tech.powerjob.worker.actors.TroubleshootingActor - [TroubleshootingActor] receive DeadLetter: DeadLetter(TaskTrackerReportInstanceStatusReq(appId=85, jobId=87, instanceId=649387666143445120, wfInstanceId=null, appendedWfContext={}, instanceStatus=5, result=应用运行正常！, totalTaskNum=1, succeedTaskNum=1, failedTaskNum=0, startTime=1710602100139, reportTime=1710602121159, sourceAddress=xx.xx.xx.xx:27777, needAlert=false, alertContent=null),Actor[akka://oms/temp/_$dj],Actor[akka://oms/deadLetters])
2024-03-16 23:15:26.160 [ctttp-649387666143445120-0] WARN  t.p.worker.core.tracker.task.CommonTaskTracker - [TaskTracker-649387666143445120] report finished status failed, result=应用运行正常！.
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:91)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:91)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.package$.blocking(package.scala:124)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:91)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.innerRun(CommonTaskTracker.java:258)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.run(CommonTaskTracker.java:324)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
···
2024-03-16 23:16:38.167 [ctttp-649387666143445120-0] ERROR t.p.worker.core.tracker.task.CommonTaskTracker - [TaskTracker-649387666143445120] try to report finished status(success=true, result=应用运行正常！) lots of times but all failed, it's time to give up, so the process result will be dropped
2024-03-16 23:16:38.168 [oms-akka.processor-tracker-dispatcher-3278] INFO  t.p.worker.core.tracker.processor.ProcessorTracker - [ProcessorTracker-649387666143445120] ProcessorTracker destroyed successfully!
2024-03-16 23:16:38.168 [ctttp-649387666143445120-0] INFO  tech.powerjob.worker.core.tracker.task.TaskTracker - [TaskTracker-649387666143445120] TaskTracker has left the world(using 1.060 ms), bye~
2024-03-16 23:16:42.766 [oms-worker-timing-pool-2] WARN  t.p.worker.background.ServerDiscoveryService - [PowerDiscovery] can't find any available server, this worker[appId=85] has been quarantined.

**Expected behavior**
项目稳定运行了进一年多时间，未出现异常，近期突然出现两次 work 全部无法连接 server 端情况。server 做了三台集群 ，项目有十来个，也同样集群部署。powerjob-server服务端重启后恢复。排查 server 日志未出现异常情况，work 端出现上诉日志异常，  因大部分老项目 ，都使用的 akka 通讯 

查看数据库 大部分应用都注册在同一台机器上，项目配置集群地址（随机设置的顺序），选举方式能否让 work分布在多台服务呢 

**Environment**
 - PowerJob Version: [e.g. 4.3.3]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 6]

**Screenshots**

**Additional context**

**Comment by andychyiyi** [comment]
有解决方案吗？
我也遇到同样的问题了。稳定运行很久后出现lots of times but all failed, it's time to give up, so the process result will be dropped

**Comment by davidshi-debug** [comment]
有解决方案吗？也是同样的问题
