### ISSUE TITLE
任务执行完成上报完成状态时出现lots of times but all failed, it's time to give up, so the process result will be dropped

### ISSUE THREAD

**Issue by wuweihongdd** [PowerJob/PowerJob#920]
unt       | maxDeltaGCCount    | minDeltaGCCount    | totalGCTime        | maxDeltaGCTime     | minDeltaGCTime     		 PS MarkSweep         | 0                  | 0                  | 0                  | 0.000s             | 0.000s             | 0.000s             		 PS Scavenge          | 0                  | 0                  | 0                  | 0.000s             | 0.000s             | 0.000s             2024-06-06 11:33:57.552 [job-0] INFO  JobContainer - PerfTrace not enable!2024-06-06 11:33:57.552 [job-0] INFO  StandAloneJobContainerCommunicator - 总数 0 条, 0 字节 | 速度 0B/s, 0 条/s | 错误 0 条, 0 字节 |  任务等待写的时间0.000s |  任务等待读的时间 0.000s | 2024-06-06 11:33:57.553 [job-0] INFO  JobContainer - 任务启动时刻                    : 2024-06-06 11:33:46任务结束时刻                    : 2024-06-06 11:33:57任务总计耗时                    :               10(s)任务平均流量                    :                0B/s记录写入速度                    :              0rec/s读出记录总数                    :                  0条读写失败总数                    :                  0条2024-06-06 11:33:57.553 [job-0] INFO  JobContainer - stopSchedule被调用...2024-06-06 11:33:57.553 [job-0] INFO  AbstractScheduler - AbstractScheduler stop被调用2024-06-06 11:33:57.553 [job-0] ERROR TaskGroupContainer - TaskGroupContainer stop被调用..
11:33:57.600[powerjob-worker-light-task-execute-374]INFO  com.chinacreator.bdg.common.utils.DriverManagerUtil - 已强制设置java.sql.DriverManager 的全局[驱动程序在尝试连接到数据库时等待的最长时间]为：3600秒
11:33:57.609[powerjob-worker-light-task-execute-374]INFO  tech.powerjob.worker.core.tracker.task.light.LightTaskTracker - [TaskTracker-678927058130174144] task complete ! create time:1717644826012,queue time:171,use time:11426,result:ProcessResult(success=true, msg=result:{"afterWriteTotalCount":0,"instanceId":678927058130174144,"readNum":0,"writeNum":0,"progress":1.0,"taskId":33726}, runtimeInfo=null)
11:34:02.628[powerjob-worker-light-task-execute-374]WARN  tech.powerjob.worker.core.tracker.task.TaskTracker - [TaskTracker-678927058130174144] report finished status failed, req=TaskTrackerReportInstanceStatusReq(appId=2, jobId=33726, instanceId=678927058130174144, wfInstanceId=null, appendedWfContext=null, instanceStatus=5, result=result:{"afterWriteTotalCount":0,"instanceId":678927058130174144,"readNum":0,"writeNum":0,"progress":1.0,"taskId":33726}, runtimeInfoUpdateStrategy=null, runtimeInfo=null, totalTaskNum=1, succeedTaskNum=1, failedTaskNum=0, startTime=1717644826012, endTime=1717644837609, reportTime=1717644837610, sourceAddress=10.200.1.6:27777, needAlert=false, alertContent=null).
java.util.concurrent.ExecutionException: akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://oms-server@10.200.1.3:10086/), Path(/user/server_actor)]] after [5000 ms]. Message of type [tech.powerjob.common.request.TaskTrackerReportInstanceStatusReq]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:91)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:91)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.package$.blocking(package.scala:124)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:91)
	at tech.powerjob.worker.common.utils.TransportUtils.reliableAsk(TransportUtils.java:116)
	at tech.powerjob.worker.common.utils.TransportUtils.reliableAsk(TransportUtils.java:107)
	at tech.powerjob.worker.common.utils.TransportUtils.reliableTtReportInstanceStatus(TransportUtils.java:93)
	at tech.powerjob.worker.core.tracker.task.TaskTracker.reportFinalStatusThenDestroy(TaskTracker.java:139)
	at tech.powerjob.worker.core.tracker.task.light.LightTaskTracker.checkAndReportStatus(LightTaskTracker.java:311)
	at tech.powerjob.worker.core.tracker.task.light.LightTaskTracker.processTask(LightTaskTracker.java:245)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://oms-server@10.200.1.3:10086/), Path(/user/server_actor)]] after [5000 ms]. Message of type [tech.powerjob.common.request.TaskTrackerReportInstanceStatusReq]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
11:34:08.166[powerjob-worker-light-task-status-check-916]INFO  tech.powerjob.worker.core.tracker.task.TaskTracker - [TaskTracker-678927058130174144] report finished status(detail=TaskTrackerReportInstanceStatusReq(appId=2, jobId=33726, instanceId=678927058130174144, wfInstanceId=null, appendedWfContext=null, instanceStatus=5, result=result:{"afterWriteTotalCount":0,"instanceId":678927058130174144,"readNum":0,"writeNum":0,"progress":1.0,"taskId":33726}, runtimeInfoUpdateStrategy=null, runtimeInfo=null, totalTaskNum=1, succeedTaskNum=1, failedTaskNum=0, startTime=1717644826012, endTime=1717644837609, reportTime=1717644848151, sourceAddress=10.200.1.6:27777, needAlert=false, alertContent=null)) success
11:34:08.166[powerjob-worker-light-task-status-check-916]WARN  tech.powerjob.worker.core.tracker.task.light.LightTaskTracker - [TaskTracker-678927058130174144] remove TaskTracker,task status WORKER_PROCESS_SUCCESS,start time:1717644826183,end time:1717644837609,real cost:11426,total time:22154
![a8f577fe5cb484e82fe20e1a063a98f](https://github.com/PowerJob/PowerJob/assets/26009818/df4f5710-b24e-4ec0-9b5f-8e4c98deba09)

**Comment by KFCFans** [comment]
和 server 之间的通讯出问题了，结果无法回传到 server。网络库底层应该有报错，错误日志可以找找。

官方文档之前有个错误，让大家配置的 logger 路径是 `tech.powerjob.worker`，导致网络库的日志无法输出了。可以改成 `tech.powerjob` 后重新查看下日志，或者去其他地方找找。

<img width="857" alt="image" src="https://github.com/user-attachments/assets/dafc3ec6-dee9-4e62-8ba5-a967192aa511">

**Comment by KFCFans** [comment]
找到错误日志堆栈后可以继续反馈
