### ISSUE TITLE
线上环境，运行一段时间，cpu飙高 ProcessorTrackerPool.removeProcessorTracker

### ISSUE THREAD

**Issue by 17729389320** [PowerJob/PowerJob#924]
版本：3.2.2
以下是采用arthas监控，导致cpu飙高的线程堆栈信息。
"oms-akka.processor-tracker-dispatcher-13900" Id=141675 cpuUsage=99.64% deltaTime=201ms time=17274036ms RUNNABLE
    at java.util.HashMap$TreeNode.find(HashMap.java:1905)
    at java.util.HashMap$TreeNode.getTreeNode(HashMap.java:1913)
    at java.util.HashMap.removeNode(HashMap.java:825)
    at java.util.HashMap.remove(HashMap.java:800)
    at com.github.kfcfans.powerjob.worker.core.tracker.processor.ProcessorTrackerPool.removeProcessorTracker(ProcessorTrackerPool.java:46)
    at com.github.kfcfans.powerjob.worker.actors.ProcessorTrackerActor.onReceiveTaskTrackerStopInstanceReq(ProcessorTrackerActor.java:61)
    at com.github.kfcfans.powerjob.worker.actors.ProcessorTrackerActor$$Lambda$1740/892638706.apply(Unknown Source)
    at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
    at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
    at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
    at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
    at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:242)
    at akka.actor.Actor.aroundReceive(Actor.scala:534)
    at akka.actor.Actor.aroundReceive$(Actor.scala:532)
    at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
    at akka.actor.ActorCell.invoke(ActorCell.scala:543)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
    at akka.dispatch.Mailbox.run(Mailbox.scala:230)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

<img width="1202" alt="image" src="https://github.com/PowerJob/PowerJob/assets/32485693/9cfce631-e9e7-4f31-98f3-1022a3cc4d0f">

**Comment by 17729389320** [comment]
已解决同问题：https://github.com/PowerJob/PowerJob/issues/122
