### ISSUE TITLE
出现 create root task failed 错误

### ISSUE THREAD

**Issue by bingfengwx** [PowerJob/PowerJob#954]
系统一直稳定运行，但今天出现一次 create root task failed 错误。请 @KFCFans 帮忙看看是什么原因。谢谢！

```
[uspyx:10.200.2.245:8090] 2024-08-01 14:58:02.265 ERROR 8 [oms-akka.task-tracker-dispatcher-54379] tech.powerjob.worker.core.tracker.task.CommonTaskTracker [TaskTracker-699271319841145472] create root task failed.
[uspyx:10.200.2.245:8090] 2024-08-01 14:58:02.265 ERROR 8 [oms-akka.task-tracker-dispatcher-27618] tech.powerjob.worker.persistence.TaskPersistenceService [TaskPersistenceService] save task{taskId='0', instanceId=699271322689077888, subInstanceId=699271322689077888, taskName='OMS_ROOT_TASK', address='10.200.2.245:27777', status=1, result='null', failedCnt=0, createdTime=1722495392063, lastModifiedTime=1722495392063, lastReportTime=-1} failed.

java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at tech.powerjob.worker.persistence.ConnectionFactory.getConnection(ConnectionFactory.java:32)
	at tech.powerjob.worker.persistence.TaskDAOImpl.save(TaskDAOImpl.java:42)
	at tech.powerjob.worker.persistence.TaskPersistenceService.lambda$save$0(TaskPersistenceService.java:54)
	at tech.powerjob.common.utils.CommonUtils.executeWithRetry(CommonUtils.java:45)
	at tech.powerjob.worker.persistence.TaskPersistenceService.execute(TaskPersistenceService.java:349)
	at tech.powerjob.worker.persistence.TaskPersistenceService.save(TaskPersistenceService.java:54)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker.persistenceRootTask(CommonTaskTracker.java:134)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker.initTaskTracker(CommonTaskTracker.java:73)
	at tech.powerjob.worker.core.tracker.task.TaskTracker.<init>(TaskTracker.java:139)
	at tech.powerjob.worker.core.tracker.task.CommonTaskTracker.<init>(CommonTaskTracker.java:61)
	at tech.powerjob.worker.core.tracker.task.TaskTracker.create(TaskTracker.java:158)
	at tech.powerjob.worker.actors.TaskTrackerActor.lambda$onReceiveServerScheduleJobReq$2(TaskTrackerActor.java:136)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at tech.powerjob.worker.core.tracker.task.TaskTrackerPool.atomicCreateTaskTracker(TaskTrackerPool.java:32)
	at tech.powerjob.worker.actors.TaskTrackerActor.onReceiveServerScheduleJobReq(TaskTrackerActor.java:136)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:242)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:188)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2538)
	at org.h2.engine.Database.open(Database.java:709)
	at org.h2.engine.Database.openDatabase(Database.java:286)
	at org.h2.engine.Database.<init>(Database.java:280)
	at org.h2.engine.Engine.openSession(Engine.java:66)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:119)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/root/powerjob/worker/h2/4e29c45c8b514eae9b23a96c9c9fe5f5/powerjob_worker_db.mv.db [1.4.197/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
	at org.h2.mvstore.FileStore.open(FileStore.java:168)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:350)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	... 25 common frames omitted
Caused by: java.nio.channels.OverlappingFileLockException: null
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.h2.mvstore.FileStore.open(FileStore.java:165)
	... 28 common frames omitted
```

**Comment by KFCFans** [comment]
<img width="887" alt="image" src="https://github.com/user-attachments/assets/ebf51b7e-6699-4e0c-8715-c00b99ab852c">

可以重点排查下1和3，是不是数据库文件被其他进程占用了。

**Comment by KFCFans** [comment]
常见问题有：
* 定时清理任务把这个文件误删了或锁定了
* 全盘扫描进程锁定了这个文件等等

这个错误应该来源于外部，非 worker 本身内部导致的异常。如果任务量不大，不需要用到大规模 MR，也可以考虑用内存模式，这样就不会有磁盘的访问行为。

`powerjob.worker.store-strategy=memory`
`tech.powerjob.worker.common.PowerJobWorkerConfig#storeStrategy`

**Comment by bingfengwx** [comment]
已找到原因，非常感谢！

**Comment by luopingLgf** [comment]
请问一下怎么解决的？

**Comment by luopingLgf** [comment]
> 已找到原因，非常感谢！

请问下 是什么原因导致的？ 怎么解决的？
