### ISSUE TITLE
springboot3.2.8启动时 有时会报错导致程序无法运行

### ISSUE THREAD

**Issue by Lwc-0917** [PowerJob/PowerJob#966]
[2024-08-12 19:25:03]|ERROR|[][] main tech.powerjob.worker.PowerJobWorker 138 init [PowerJobWorker] initialize PowerJobWorker failed, using 362.2 ms.
java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:216)
	at io.vertx.core.file.impl.FileCache.registerShutdownHook(FileCache.java:80)
	at io.vertx.core.file.impl.FileCache.setupCache(FileCache.java:33)
	at io.vertx.core.file.impl.FileResolverImpl.<init>(FileResolverImpl.java:67)
	at io.vertx.core.impl.VertxBuilder.initFileResolver(VertxBuilder.java:334)
	at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:274)
	at io.vertx.core.Vertx.vertx(Vertx.java:87)
	at tech.powerjob.remote.http.vertx.VertxInitializer.buildVertx(VertxInitializer.java:39)
	at tech.powerjob.remote.http.HttpVertxCSInitializer.init(HttpVertxCSInitializer.java:79)
	at tech.powerjob.remote.framework.engine.impl.PowerJobRemoteEngine.start(PowerJobRemoteEngine.java:42)
	at tech.powerjob.worker.PowerJobWorker.init(PowerJobWorker.java:113)
	at tech.powerjob.worker.PowerJobSpringWorker.afterPropertiesSet(PowerJobSpringWorker.java:40)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at com.yuanxinwallet.Application.main(Application.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

**Comment by KFCFans** [comment]
java.lang.IllegalStateException: Shutdown in progress

看错误应该是别的组件启动失败，导致 vertx 启动到一半就要销毁了。不是 powerjob-worker 直接导致的启动失败。

我在对应版本的 Spring 测试了下也是没问题的。
